### ISSUE TITLE
ARM64 Linux VMs stuck on 'EFI stub: Exiting boot services and installing virtual address map...'

### ISSUE THREAD

**Issue by lTheMightyMl** [utmapp/UTM#2682]
I've tried installing Debian 10.9, 9.13 and openSUSE 15.3 on ARM64 virt machine following the instructions in [the gallery](https://mac.getutm.app/gallery/ubuntu-20-04) and [this related issue](https://github.com/utmapp/UTM/issues/2333), but all of them end up stalling when selecting the 'install' option from the installation media, with Debian 9.13 and openSUSE 15.3 showing this before stalling:

<img width="1440" alt="Screen Shot 1400-05-03 at 08 51 39" src="https://user-images.githubusercontent.com/21312503/126888443-06ba4877-cac7-40a8-96d4-d236c99d11cd.png">

**Configuration**
* UTM Version: 2.1.2
* OS Version: 11.4
* Intel or Apple Silicon? Apple Silicon M1

openSUSE log: [debug.log](https://github.com/utmapp/UTM/files/6873405/debug.log)

openSUSE config: [config.plist](https://github.com/utmapp/UTM/files/6873403/config.txt)

Update: Ubuntu 20.04.2 and Kali 2021.2 for Apple M1 work fine. Seems to be a problem with the OSes not supporting M1 processors.

**Comment by conath** [comment]
To confirm it is an M1 incompatibility, you could check the box "Force slower emulation even when hypervisor is available" in UTM Preferences (Menu UTM => Preferences…).
<img width="508" alt="Screen Shot 2021-08-10 at 23 07 20" src="https://user-images.githubusercontent.com/12073163/128935161-206cb60e-eba1-4e3b-a079-26aa2fc48720.png">

**Comment by cseelus** [comment]
Same problem with Ubuntu 20.04.2 Server, even with 'Force slower emulation even when hypervisor is available' enabled.

![Screen Shot 2021-08-18 at 19 31 33](https://user-images.githubusercontent.com/3188392/129945076-b3afe613-f971-44af-b092-e7f469d73bfc.png)

**Comment by conath** [comment]
@cseelus On my M1 MacBook Pro I wa danke to install Ubuntu Server ARM 20.04 just fine, following the [instructions](https://github.com/utmapp/UTM/wiki/Install%20Ubuntu%20ARM64%20on%20Apple%20M1). How did you install it?

**Comment by cseelus** [comment]
Weird, also followed the instructions one by one. Using Debian for now, which works fine (including networking).

**Comment by jeffersfp** [comment]
I've faced this issue while attempting a fresh install of a ubuntu xenial install. Changing the Display mode to "Console Only" has solved it.

**Comment by jeffersfp** [comment]
I recorded the step-by-step in order to provide some evidence on how to reproduce this error:

- full graphics

https://user-images.githubusercontent.com/8990515/130292869-cf15948b-e074-45fb-a805-bc311764ddde.mp4

i did stop the video as soon as the message pops up but it stays stuck in this state forever

- console only (same vm, simply changed display mode)

https://user-images.githubusercontent.com/8990515/130292886-2507f581-4a8e-4e1b-b3e4-5f8bff1637b3.mp4

the iso image i'm using is the following: https://cdimage.ubuntu.com/releases/16.04.7/release/ubuntu-16.04.4-server-arm64.iso

the sha256sum matches with the checksum available at https://cdimage.ubuntu.com/releases/16.04.7/release/SHA256SUMS

![image](https://user-images.githubusercontent.com/8990515/130293099-9b33b639-1da8-4f8c-acc0-006b83875dc9.png)

![image](https://user-images.githubusercontent.com/8990515/130293133-6675278d-5e38-46c8-8dc4-b3b1db293518.png)

i'm no expert but it looks like the problems is related to the distro version that might be missing some video drivers or something... ubuntu 18 and 20 works fine when display mode is set up to full graphics mode

**Comment by conath** [comment]
@jeffersfp Indeed it has been reported previously that versions of Ubuntu older than 20 don't work with recent UTM/QEMU (I have not looked into it).

One thing you could try is to play around with the graphics cards choices available and see if any of them allow you to install it.

**Comment by yyyyy12** [comment]
Same issue. How can I solve it....?

**Comment by Shiaoli** [comment]
same issue here. Apple M1 + Ubuntu 20.04 ARM64. It worked well for a while and then this error came out.

**Comment by SebDanielsson** [comment]
Same issue with Fedora 35. Has anyone created an issue for this problem over att Fedora? Ubuntu 21.10 works perfect with macOS Monterey, UTM 2.4.0 on my M1 Mac.

**Comment by fmarzocca** [comment]
same on Macbook air M1 and Monterey (Ubuntu server)

**Comment by vollmerf** [comment]
Same on 2021 MacBook Pro M1 and Monterey (Ubuntu server). It booted once, but is now failing.

**Comment by jeffersfp** [comment]
**Note for Ubuntu users:** I've been using [Multipass](https://multipass.run/) to run Ubuntu server instances. UTM works great but if all you need is a quick way to spin up Ubuntu instances on the m1 mac, then Multipass is the solution at the time of this message. I was also able to use Vagrant with Multipass as a provider by using this [plugin](https://github.com/Fred78290/vagrant-multipass). If you need Ubuntu with GUI or any other linux distro then UTM is the way to go.

**Comment by avibrazil** [comment]
I struggled with Fedora 35 ARM installation in M1.

Solution was:

1. Disable graphics console, go text only, as [suggested above](https://github.com/utmapp/UTM/issues/2682#issuecomment-902947359)
2. [Configure Fedora to be installed via VNC](https://docs.fedoraproject.org/en-US/fedora/f35/install-guide/advanced/VNC_Installations/), in order to use UTM window as text only and have graphics over VNC
3. Use your macOS Screen Sharing app to connect via VNC to the graphical installation (use VM declared IP and port 5901 to connect).

Result is like the screen shot

<img width="1136" alt="Screen Shot 2021-12-22 at 23 37 34" src="https://user-images.githubusercontent.com/3484242/147180156-33d29408-1ff4-4a8c-933c-6d801ead69e4.png">

**Comment by samuela** [comment]
I'm seeing the same issue here. I had a working NixOS VM running (aarch64 guest, aarch64-darwin host). Rebooting the machine from inside the guest got stuck and now I have this forever `EFI stub:` issue.

Any known workarounds/fixes? I tried the "Force slower emulation..." option to no avail. That options just gives me a forever black screen... no UTM splash screen at boot, etc.

**Comment by samuela** [comment]
I don't know if this is relevant but at the time that it hangs there is a "QEMULauncher" processes spinning like crazy at constant 100% CPU.

**Comment by samuela** [comment]
Another thing that doesn't work: deleting/backing up the `efi_vars.fd` file

**Comment by samuela** [comment]
https://github.com/albertyw/albertyw.com/blob/dbf68c6b5939e05b5f2ab86288b75c32b323c3c5/app/notes/20211211-1933.md appears to be relevant

**Comment by samuela** [comment]
Solution that worked for me:
* Attach an installer ISO and boot into it.
* Run `sudo fsck /dev/disk/by-label/<your disk>`
* Shut down, disconnect the ISO, and reboot into your VM.
* Always always always perform shutdowns from within the guest VM itself!

**Comment by inust33** [comment]
no solution yet?

**Comment by inust33** [comment]
no solution yet?

**Comment by inust33** [comment]
@samuela 

> Solution that worked for me:
> 
> * Attach an installer ISO and boot into it.
> * Run `sudo fsck /dev/disk/by-label/<your disk>`
> * Shut down, disconnect the ISO, and reboot into your VM.
> * Always always always perform shutdowns from within the guest VM itself!

thanks for your post, I tried the fsck /dev/mapper command in the post but 
```error 2 (No such file or directory) while executing fsck.ext2 for /dev/mapper/ubuntu--vg-root```
do you have any other idea?

**Comment by BrodaUa** [comment]
Having the same issue as the user https://github.com/utmapp/UTM/issues/2682#issuecomment-987204910
Running Mac Pro 14' M1 with Monterey 12.1, UTM: 3.0.4-2 installed via brew.
The difference for me is that after following the installation process, I press Reboot now, it gets stuck with black screen and unresponsive '_' (underscore). After forcing the VM shutdown via UTM interface, detaching the Installer ISO, starting the VM shows again the 'Start boot option' and after a while 'EFI stub: Exiting boot services and installing virtual address map...' frozen screen.

**Comment by avibrazil** [comment]
Folks, this problem has a [palliative solution just to get you going](https://github.com/utmapp/UTM/issues/2682#issuecomment-1000002827).

[I wrote about it here a few comment above.](https://github.com/utmapp/UTM/issues/2682#issuecomment-1000002827)

Basically you have to disable graphics in your VM.

**Comment by tandon** [comment]
I can reproduce this on a M1 Mac, with Ubuntu, Kali, any version of either. The issue is specifically that console/text-only mode works just fine, and the OS fully installs. No problem, until... shutting down, then toggling UTM preference for the VM back to graphical mode, using *any* option of graphic card emulation, leads to a machine that does not boot, stops exactly as others have noted, at 'EFI stub: Exiting boot services and installing virtual address map...' then nothing happens, even if the machine is left for hours. 

No useful errors in the UTM debug output. QEMU version 6.2.

**Comment by marchaase** [comment]
I've been trying to get a LUKS full disk encryption setup working with UTM on an M1 MacBook.  If I use the text only console it works and will boot, but am unable to get it working with graphics at all.  It almost seems like the normal boot logs you would see before it enters graphics mode don't show up and that's where I need to type the disk encryption password... =(

**Comment by johnparcia** [comment]
> https://github.com/albertyw/albertyw.com/blob/dbf68c6b5939e05b5f2ab86288b75c32b323c3c5/app/notes/20211211-1933.md appears to be relevant

Hi, can anyone help me with this one? When I boot with console-mode, I'm booted into GNU GRUB and not a "BareBox bootloader."

**Comment by QuentinGuyot-epitech** [comment]
> Hello guys I had similar issue and what helped is converting image and then importing again as new utm machine.. Something like: qemu-img convert /Users//Library/Containers/com.utmapp.UTM/Data/Documents/Linux.utm/Images/data.raw ~/Documents/data.raw
> 
> So I guess the problem is in efi_vars.fd or something like that as image itself is fine if you import it again..

I try this but no luck for me. I have an image named disk-0.qcow2 trying to qemu-img convert to .raw or also .qcow2 but can't import the vm after that UTM saying configuration pb no possible to import it....

**Comment by gaborcsardi** [comment]
I am seeing this as well. It was working for a couple of weeks, and then the network was gone, so I rebooted it, and now it does not boot at all. 

Disabling graphics mode does not help, and fsck says that the disks are clean.

Ubuntu 20.04 VM, M1 Monterey.

**Comment by osy** [comment]
This is an old issue and I don’t think what people who are commenting based off of 3.X is relevant.

Can someone please open a new issue with all the requested information (version, logs, etc)?

**Comment by osy** [comment]
I've root caused the issue: https://gitlab.com/qemu-project/qemu/-/issues/899

It is Linux 5.4.0-104. Here is a temporary workaround (skip steps 1-4 if the VM worked previously and only stopped booting recently):

1. Open the VM settings and under QEMU -> Tweaks, uncheck "Use Hypervisor"
2. Boot into Linux, but it will be VERY slow because it is using emulation instead of virtualization.
3. Once inside, install the last version of Linux `sudo apt install linux-image-5.4.0-100-generic`
4. Shut down the VM, open VM settings and under QEMU -> Teaks, check "Use Hypervisor" to re-enable virtualization.
5. Start the VM and when the UTM logo shows up, hold "Shift" to enter the GRUB menu
6. Select "Advanced Options for Ubuntu"
7. Select "Ubuntu, with Linux 5.4.0-100-generic" (or anything lower than 5.4.0-104)
8. You can now boot into Ubuntu again. You may choose to uninstall 5.4.0-104 and temporarily mask it from being updated in the future.

Hopefully this issue can be fixed in QEMU and we can provide an update in the future.

**Comment by youronlinefriend** [comment]
> I've root caused the issue: https://gitlab.com/qemu-project/qemu/-/issues/899
> 
> It is Linux 5.4.0-104. Here is a temporary workaround (skip steps 1-4 if the VM worked previously and only stopped booting recently):
> 
> 1. Open the VM settings and under QEMU -> Tweaks, uncheck "Use Hypervisor"
> 2. Boot into Linux, but it will be VERY slow because it is using emulation instead of virtualization.
> 3. Once inside, install the last version of Linux `sudo apt install linux-image-5.4.0-100-generic`
> 4. Shut down the VM, open VM settings and under QEMU -> Teaks, check "Use Hypervisor" to re-enable virtualization.
> 5. Start the VM and when the UTM logo shows up, hold "Shift" to enter the GRUB menu
> 6. Select "Advanced Options for Ubuntu"
> 7. Select "Ubuntu, with Linux 5.4.0-100-generic" (or anything lower than 5.4.0-104)
> 8. You can now boot into Ubuntu again. You may choose to uninstall 5.4.0-104 and temporarily mask it from being updated in the future.
> 
> Hopefully this issue can be fixed in QEMU and we can provide an update in the future.

This was the furthers I got. I tried to use apt to install the linux image but I got errors because ports.ubuntu.com could not be reached. I pinged 8.8.8.8 and got network is unreachable. Then I pinged 127.0.0.1 and got replies. My network is shared network and virtio-net-pc. I tried emulated and bridged. None seem to work. It seems this VM is not working right with my guest network.

**Comment by parmijohno** [comment]
> 

Hi! How do I uninstall 5.4.0-104 or temporarily mask it from being updated in the future?

**Comment by sokurenko** [comment]
I upgraded to ubuntu 21 some time ago and it works much better, for week no such issues.

**Comment by osy** [comment]
For network issues see troubleshooting https://mac.getutm.app/gallery/ubuntu-20-04

**Comment by osy** [comment]
> Hi! How do I uninstall 5.4.0-104 or temporarily mask it from being updated in the future?

`sudo apt-mark hold linux-image-$(uname -r)`

**Comment by Takiro021** [comment]
**Problem:**
My VM(**Ubuntu 20.04**) worked perfectly and after 2 weeks I faced this problem(my device: **Macbook pro M1, 2020**):
![Screenshot 2022-03-11 at 12 21 48](https://user-images.githubusercontent.com/54674140/157857838-bca92855-95ee-4e64-91af-25b8145cf255.png)

**Solution:** 

1. go to your VM setting and select **Console only** and then save. (don't forget to disable the **sound** in the VM settings otherwise you will get an error)
2. start the VM again and now you should see the console
3. run **fsck -y /dev/mapper/ubuntu--vg-ubuntu--lv**
4. now run **exit**
5. change your VM settings from **Console only** to **Full screen**
6. now run the VM

I hope this works for you!!

**Comment by arag0re** [comment]
> **Problem:** My VM(**Ubuntu 20.04**) worked perfectly and after 2 weeks I faced this problem(my device: **Macbook pro M1, 2020**): ![Screenshot 2022-03-11 at 12 21 48](https://user-images.githubusercontent.com/54674140/157857838-bca92855-95ee-4e64-91af-25b8145cf255.png)
> 
> **Solution:**
> 
> 1. go to your VM setting and select **Console only** and then save. (don't forget to disable the **sound** in the VM settings otherwise you will get an error)
> 2. start the VM again and now you should see the console
> 3. run **fsck -y /dev/mapper/ubuntu--vg-ubuntu--lv**
> 4. now run **exit**
> 5. change your VM settings from **Console only** to **Full screen**
> 6. now run the VM
> 
> I hope this works for you!!

didnt work for me unfortunately

**Comment by Takiro021** [comment]
> > **Problem:** My VM(**Ubuntu 20.04**) worked perfectly and after 2 weeks I faced this problem(my device: **Macbook pro M1, 2020**): ![Screenshot 2022-03-11 at 12 21 48](https://user-images.githubusercontent.com/54674140/157857838-bca92855-95ee-4e64-91af-25b8145cf255.png)
> > **Solution:**
> > 
> > 1. go to your VM setting and select **Console only** and then save. (don't forget to disable the **sound** in the VM settings otherwise you will get an error)
> > 2. start the VM again and now you should see the console
> > 3. run **fsck -y /dev/mapper/ubuntu--vg-ubuntu--lv**
> > 4. now run **exit**
> > 5. change your VM settings from **Console only** to **Full screen**
> > 6. now run the VM
> > 
> > I hope this works for you!!
> 
> didnt work for me unfortunately

Can you explain your issue or show some screenshots?

**Comment by AndreaPrati98** [comment]
> 

It seemed to work for me. In fact I have been able to install ubuntu server and grub.

Now, also if using, the hypervisor, I am able to access ubuntu server throughout linux-5.4.0-100, BUT, unfortunately, the command `apt` seems not working anymore. The network is not connected, neither `ping 8.8.8.8` works
<img width="800" alt="Schermata 2022-03-11 alle 16 18 40" src="https://user-images.githubusercontent.com/62189267/157895610-763f7b0f-3f1c-4d25-91b6-12f3e3f2f4bd.png">


I have tried simple solutions like updating the DNS but it seems a bigger problem

**Comment by arag0re** [comment]
Idk for me it was easier to just use Ubuntu 21.04 cause i didn't need 20.04 specifically

**Comment by iSamBa** [comment]
I am facing the same problem, and I really need 20.04 specifically !! :(

**Comment by osy** [comment]
> I've root caused the issue: https://gitlab.com/qemu-project/qemu/-/issues/899
> 
> It is Linux 5.4.0-104. Here is a temporary workaround (skip steps 1-4 if the VM worked previously and only stopped booting recently):
> 
> 1. Open the VM settings and under QEMU -> Tweaks, uncheck "Use Hypervisor"
> 2. Boot into Linux, but it will be VERY slow because it is using emulation instead of virtualization.
> 3. Once inside, install the last version of Linux `sudo apt install linux-image-5.4.0-100-generic`
> 4. Shut down the VM, open VM settings and under QEMU -> Teaks, check "Use Hypervisor" to re-enable virtualization.
> 5. Start the VM and when the UTM logo shows up, hold "Shift" to enter the GRUB menu
> 6. Select "Advanced Options for Ubuntu"
> 7. Select "Ubuntu, with Linux 5.4.0-100-generic" (or anything lower than 5.4.0-104)
> 8. You can now boot into Ubuntu again. You may choose to uninstall 5.4.0-104 and temporarily mask it from being updated in the future: `sudo apt-mark hold linux-image-$(uname -r)`
> 
> Hopefully this issue can be fixed in QEMU and we can provide an update in the future.

Did this not work?

**Comment by milindsoorya** [comment]
> I've root caused the issue: https://gitlab.com/qemu-project/qemu/-/issues/899
> 
> It is Linux 5.4.0-104. Here is a temporary workaround (skip steps 1-4 if the VM worked previously and only stopped booting recently):
> 
> 1. Open the VM settings and under QEMU -> Tweaks, uncheck "Use Hypervisor"
> 2. Boot into Linux, but it will be VERY slow because it is using emulation instead of virtualization.
> 3. Once inside, install the last version of Linux `sudo apt install linux-image-5.4.0-100-generic`
> 4. Shut down the VM, open VM settings and under QEMU -> Teaks, check "Use Hypervisor" to re-enable virtualization.
> 5. Start the VM and when the UTM logo shows up, hold "Shift" to enter the GRUB menu
> 6. Select "Advanced Options for Ubuntu"
> 7. Select "Ubuntu, with Linux 5.4.0-100-generic" (or anything lower than 5.4.0-104)
> 8. You can now boot into Ubuntu again. You may choose to uninstall 5.4.0-104 and temporarily mask it from being updated in the future: `sudo apt-mark hold linux-image-$(uname -r)`
> 
> Hopefully this issue can be fixed in QEMU and we can provide an update in the future.

Just by unchecking the hypervisor I got it to work. thanks.

**Comment by osy** [comment]
Fixed in v3.1.5

**Comment by dhirajpatra** [comment]
yes 3.1.5 fixed the issue for Ubuntu boot after installation. thanks a lot

**Comment by taitleaney** [comment]
> I've root caused the issue: https://gitlab.com/qemu-project/qemu/-/issues/899
> 
> It is Linux 5.4.0-104. Here is a temporary workaround (skip steps 1-4 if the VM worked previously and only stopped booting recently):
> 
>     1. Open the VM settings and under QEMU -> Tweaks, uncheck "Use Hypervisor"
> 
>     2. Boot into Linux, but it will be VERY slow because it is using emulation instead of virtualization.
> 
>     3. Once inside, install the last version of Linux `sudo apt install linux-image-5.4.0-100-generic`
> 
>     4. Shut down the VM, open VM settings and under QEMU -> Teaks, check "Use Hypervisor" to re-enable virtualization.
> 
>     5. Start the VM and when the UTM logo shows up, hold "Shift" to enter the GRUB menu
> 
>     6. Select "Advanced Options for Ubuntu"
> 
>     7. Select "Ubuntu, with Linux 5.4.0-100-generic" (or anything lower than 5.4.0-104)
> 
>     8. You can now boot into Ubuntu again. You may choose to uninstall 5.4.0-104 and temporarily mask it from being updated in the future: `sudo apt-mark hold linux-image-$(uname -r)`
> 
> 
> Hopefully this issue can be fixed in QEMU and we can provide an update in the future.

I had a similar issue, I think to do with linux 5.35. I chose advanced Ubuntu settings and selected linux 5.30 instead and was able to boot to the login gui

**Comment by milindsoorya** [comment]
> 

I was only able to boot into Ubuntu after changing the following settings in the UTM options:
1. Disabling the QMEU > use hypervisor option
2. Changing the display type to Console only 

The above solution worked to fix the boot issue, but now the internet connection doesn't seem to be working. I tried changing DNS as shown in this [discussion](https://github.com/utmapp/UTM/discussions/2435) but its not working.

**Comment by AndreaPrati98** [comment]
> I was only able to boot into Ubuntu after changing the following settings in the UTM options:
> 
> 1. Disabling the QMEU > use hypervisor option
> 2. Changing the display type to Console only
> 
> The above solution worked to fix the boot issue, but now the internet connection doesn't seem to be working. I tried changing DNS as shown in this [discussion](https://github.com/utmapp/UTM/discussions/2435) but its not working.

Have you tried to download the new release of UTM? Because I had the exact same issue as yours but using the new release solved every problem without change a single setting!

For the seek of honesty, the error is still displayed in my monitor, but after 10 seconds or less the vm starts anyway.
@milindsoorya

**Comment by celinehocquette** [comment]
I have had the same issue, did the following which worked:
1. Run the Virtual Machine.
2. Press Esc during boot.
3. Select "Advanced options for Ubuntu".
4. Select an older kernel version

**Comment by QuentinGuyot-epitech** [comment]
> > 
> 
> I was only able to boot into Ubuntu after changing the following settings in the UTM options:
> 
> 1. Disabling the QMEU > use hypervisor option
> 2. Changing the display type to Console only
> 
> The above solution worked to fix the boot issue, but now the internet connection doesn't seem to be working. I tried changing DNS as shown in this [discussion](https://github.com/utmapp/UTM/discussions/2435) but its not working.

Check network troubleshooting here : https://mac.getutm.app/gallery/ubuntu-20-04

**Comment by joelfinnigan** [comment]
> I've root caused the issue: https://gitlab.com/qemu-project/qemu/-/issues/899
> 
> It is Linux 5.4.0-104. Here is a temporary workaround (skip steps 1-4 if the VM worked previously and only stopped booting recently):
> 
> 1. Open the VM settings and under QEMU -> Tweaks, uncheck "Use Hypervisor"
> 2. Boot into Linux, but it will be VERY slow because it is using emulation instead of virtualization.
> 3. Once inside, install the last version of Linux `sudo apt install linux-image-5.4.0-100-generic`
> 4. Shut down the VM, open VM settings and under QEMU -> Teaks, check "Use Hypervisor" to re-enable virtualization.
> 5. Start the VM and when the UTM logo shows up, hold "Shift" to enter the GRUB menu
> 6. Select "Advanced Options for Ubuntu"
> 7. Select "Ubuntu, with Linux 5.4.0-100-generic" (or anything lower than 5.4.0-104)
> 8. You can now boot into Ubuntu again. You may choose to uninstall 5.4.0-104 and temporarily mask it from being updated in the future: `sudo apt-mark hold linux-image-$(uname -r)`
> 
> Hopefully this issue can be fixed in QEMU and we can provide an update in the future.

When you say 'you may choose to uninstall 5.4.0-104' - how would this be done? Thanks.

**Comment by osy** [comment]
You’re commenting on an outdated thread. Use 3.1.5.

**Comment by rgolab** [comment]
Unfortunately the problem seems to be not solved on `UTM 3.1.5` - I installed Ubuntu from `ubuntu-20.04.4-live-server-arm64.iso` and after installation the boot is stopped on the `EFI stub: Exiting boot services and installing virtual address map...` - the workaround with changing `Display` to `Console only` works fine

**Comment by appleseedexm** [comment]
This issue still persists with `UTM 3.1.5` and `ubuntu-20.04.4-live-server-arm64` running on `macOS Monterey 12.2.1` on a M1 MBP 2020.

Unfortunately not even console fixes the problem for me.

**Comment by gradygambrell** [comment]
me nether. when i use the `sudo apt update` it pops up errors saying it can't update after the install (i have to force restart because of the blinking line)

**Comment by t3chn0m4g3** [comment]
Having the same problem with latest Debian Bullseye and UTM 3.1.5. The workaround with turning display to console only works.

**Comment by privatekenny** [comment]
UTM 3.1.5, Ubuntu 21.10 and Linux 5.4.0-105-generic works for me with Full graphics. Takes a minute to boot up, so give it some time. On the initial ubuntu install make sure you update the kernel when you're logged in before shutting the vm down.

**Comment by RwdBass** [comment]
My issue has been tagged as a duplicate of this.
Even though my UTM is updated (version 3.1.5) and I have ubuntu-20.04.4-live-server-arm64, OS version: macOS Monterey 12.3 on an M1 MacBook Air, Ubuntu is still not functional.

after installation, I did not have a GUI, just a terminal from which I installed _xinit_ and rebooted and it opened an empty blue screen instead of the usual ubuntu desktop and all my packages are up to date.

<img width="1136" alt="Screen Shot 2022-04-04 at 10 28 15 AM" src="https://user-images.githubusercontent.com/72977353/161505662-32665867-622f-4a59-8b65-54c4a179e10a.png">
<img width="1136" alt="Screen Shot 2022-04-04 at 10 29 15 AM" src="https://user-images.githubusercontent.com/72977353/161505676-64926ef6-e9f6-4220-b51a-623cdc87d583.png">

**Comment by RwdBass** [comment]
> My issue has been tagged as a duplicate of this. Even though my UTM is updated (version 3.1.5) and I have ubuntu-20.04.4-live-server-arm64, OS version: macOS Monterey 12.3 on an M1 MacBook Air, Ubuntu is still not functional.
> 
> after installation, I did not have a GUI, just a terminal from which I installed _xinit_ and rebooted and it opened an empty blue screen instead of the usual ubuntu desktop and all my packages are up to date.
> 
> <img alt="Screen Shot 2022-04-04 at 10 28 15 AM" width="1136" src="https://user-images.githubusercontent.com/72977353/161505662-32665867-622f-4a59-8b65-54c4a179e10a.png">
> 
> <img alt="Screen Shot 2022-04-04 at 10 29 15 AM" width="1136" src="https://user-images.githubusercontent.com/72977353/161505676-64926ef6-e9f6-4220-b51a-623cdc87d583.png">

@conath Can we not have this issue as "Closed". 
Seems like just updating UTM did not fix it for some, including myself

**Comment by conath** [comment]
@RwdBass Here is a [guide on installing Ubuntu Desktop](https://github.com/utmapp/UTM/wiki/Install-Ubuntu-ARM64-on-Apple-M1#installing-ubuntu-desktop), which includes the usual applications. It might be best if you re-install Ubuntu Server (see the same guide for details if needed), then after it is installed and you are booted to Ubuntu terminal, install Ubuntu Desktop.

**Comment by t3chn0m4g3** [comment]
@conath Following the guide exactly, but it does not solve the issue. As mentioned earlier the workaround for Linux distributions with latest kernels is still necessary or machines do not boot if graphics is not set to console only.
This seems to be QEMU related since Parallels, VMWare Fusion have the same problem, but it does not occur with older kernels.

**Comment by willyaucy** [comment]
I got the same error with Ubuntu, but solved the problem by not using LVM during installation. So far I have not been able to install Ubuntu (or Fedora) with LVM on UTM.

**Comment by stackshadow** [comment]
I had the same Problem with my NixOS VM on an M1 Air. After upgrade to UTM v3.1.5 it just boots normal 👍

**Comment by wvdschel** [comment]
Still seeing this issue on M1 Mac and UTM 3.1.5.  Serial console boot works fine, graphics do not. Tried Ubuntu 20.04 &  22.04, Fedora, openSUSE, Debian. Same results. 

One thing I have seen: for me it seems like it does work fine when I disable disk encryption during install (I have two functional Ubuntu 20.04 VMs without LUKS).

I have tried various graphics devices but none work. Freebsd with disk encryption and X11 also works. 

I have tried typing in my LUKS password when it got stuck on a black screen with the terminal caret, thinking maybe it's just the early mode setting that fails and it's stuck waiting for my password, but no luck.

**Comment by brbell01** [comment]
> **Problem:** My VM(**Ubuntu 20.04**) worked perfectly and after 2 weeks I faced this problem(my device: **Macbook pro M1, 2020**): ![Screenshot 2022-03-11 at 12 21 48](https://user-images.githubusercontent.com/54674140/157857838-bca92855-95ee-4e64-91af-25b8145cf255.png)
> 
> **Solution:**
> 
> 1. go to your VM setting and select **Console only** and then save. (don't forget to disable the **sound** in the VM settings otherwise you will get an error)
> 2. start the VM again and now you should see the console
> 3. run **fsck -y /dev/mapper/ubuntu--vg-ubuntu--lv**
> 4. now run **exit**
> 5. change your VM settings from **Console only** to **Full screen**
> 6. now run the VM
> 
> I hope this works for you!!

This worked for me!  It still displayed the "EFI stub: Exiting boot services messages..." on VM startup, but it immediately moved along to the login screen.

**Comment by francois-spectre** [comment]
> > **Problem:** My VM(**Ubuntu 20.04**) worked perfectly and after 2 weeks I faced this problem(my device: **Macbook pro M1, 2020**): ![Screenshot 2022-03-11 at 12 21 48](https://user-images.githubusercontent.com/54674140/157857838-bca92855-95ee-4e64-91af-25b8145cf255.png)
> > **Solution:**
> > 
> > 1. go to your VM setting and select **Console only** and then save. (don't forget to disable the **sound** in the VM settings otherwise you will get an error)
> > 2. start the VM again and now you should see the console
> > 3. run **fsck -y /dev/mapper/ubuntu--vg-ubuntu--lv**
> > 4. now run **exit**
> > 5. change your VM settings from **Console only** to **Full screen**
> > 6. now run the VM
> > 
> > I hope this works for you!!
> 
> This worked for me! It still displayed the "EFI stub: Exiting boot services messages..." on VM startup, but it immediately moved along to the login screen.

This worked for me too! Thank you! But I had to wait several minutes before getting the system running (it was displaying an other error message about "[...](\EFI\ubuntu\shimx64.efi) Boot0005* USB Memory[...]").

**Comment by msfking** [comment]
as of today i have tried all above suggestions but only one that worked for me is quitting UTM and trying it on PARALLELS and its running well. Thanks

**Comment by msfking** [comment]
mac m1^

**Comment by ericcurtin** [comment]
Same issue on qemu (not UTM) and Automotive Stream Distribution (CentOS Stream 9 with RT kernel for automotive), tcg fixed it, but I still would like to get hvf working for native performance.

**Comment by taiko67** [comment]
> > > **Problem:** My VM(**Ubuntu 20.04**) worked perfectly and after 2 weeks I faced this problem(my device: **Macbook pro M1, 2020**): ![Screenshot 2022-03-11 at 12 21 48](https://user-images.githubusercontent.com/54674140/157857838-bca92855-95ee-4e64-91af-25b8145cf255.png)
> > > **Solution:**
> > > 
> > > 1. go to your VM setting and select **Console only** and then save. (don't forget to disable the **sound** in the VM settings otherwise you will get an error)
> > > 2. start the VM again and now you should see the console
> > > 3. run **fsck -y /dev/mapper/ubuntu--vg-ubuntu--lv**
> > > 4. now run **exit**
> > > 5. change your VM settings from **Console only** to **Full screen**
> > > 6. now run the VM
> > > 
> > > I hope this works for you!!
> > 
> > 
> > This worked for me! It still displayed the "EFI stub: Exiting boot services messages..." on VM startup, but it immediately moved along to the login screen.
> 
> This worked for me too! Thank you! But I had to wait several minutes before getting the system running (it was displaying an other error message about "[...](%5CEFI%5Cubuntu%5Cshimx64.efi) Boot0005* USB Memory[...]").

Worked for me too.  Takes a minute, but it booted. Merci!

**Comment by ericcurtin** [comment]
qemu from brew worked great for me in the end, even have a little wrapper script to do the relevant command-line options:

https://gitlab.com/CentOS/automotive/sample-images/-/blob/main/osbuild-manifests/runvm

`./runvm some_qcow2.qcow2`

or

`./runvm some_raw.raw`

**Comment by arberpolis** [comment]
> > **Problem:** My VM(**Ubuntu 20.04**) worked perfectly and after 2 weeks I faced this problem(my device: **Macbook pro M1, 2020**): ![Screenshot 2022-03-11 at 12 21 48](https://user-images.githubusercontent.com/54674140/157857838-bca92855-95ee-4e64-91af-25b8145cf255.png)
> > **Solution:**
> > 
> > 1. go to your VM setting and select **Console only** and then save. (don't forget to disable the **sound** in the VM settings otherwise you will get an error)
> > 2. start the VM again and now you should see the console
> > 3. run **fsck -y /dev/mapper/ubuntu--vg-ubuntu--lv**
> > 4. now run **exit**
> > 5. change your VM settings from **Console only** to **Full screen**
> > 6. now run the VM
> > 
> > I hope this works for you!!
> 
> This worked for me! It still displayed the "EFI stub: Exiting boot services messages..." on VM startup, but it immediately moved along to the login screen.

Thank you very much. This is actually what solved the issue for me. Good to know.

**Comment by a1ad** [comment]
FYI: You do not need to run fsck. Just boot in console type: sudo init 0 en restart VM in gui mode (Fedora 37 beta)

**Comment by anonfawkes73** [comment]
The solution worked for me too, but now my VM doesn't have access to internet anymore. Any idea? :/

**Comment by dcdebug** [comment]
> https://github.com/albertyw/albertyw.com/blob/dbf68c6b5939e05b5f2ab86288b75c32b323c3c5/app/notes/20211211-1933.md appears to be relevant

Thank you,it working.

**Comment by NerdPraise** [comment]
Reinstalling the distro without LUKS disk encryption worked for me. Same M1 Macbook pro

**Comment by MahmoudNawar** [comment]
> 

This worked for me after the issue appeared with updating ubuntu 22.04

**Comment by sifangli-labs** [comment]
The 'fsck -y ...' works for me - as a work around - and it keeps on happening whenever I need to reboot the VM - no matter how careful I try to be on how to shutdown the Ubuntu guest (on Mac M1). Since fsck really tax on the system by pretending the system's data is intact, after a while the Ubuntu image gets worse and worse.
I am using UTM 3.2.4(58), do we really have a solution?

**Comment by oglok** [comment]
I'm hitting this with Fedora 37 VM with Kernel 6.0.18. It's been working for a week, but all of the sudden, after switching off/on my Macbook PRO M1, it gets stuck at EFI stub sequence.

Any idea how to fix it?

**Comment by 123andy** [comment]
Based on previous posts - the following worked for me:

1. Shutdown and edit VM to set display to console only
2. Reboot and hold down the shift key -- this booted into busybox.  It even detected disk issues and gave me the fsck command to run, which was something like `fsck /dev/mapper/ubuntu--vg-root`
3. When prompted to approve fixes, replied with 'a' which means yes to all fixes.
4. ran `sudo shutdown -h now` to close vm
5. edited display setting of VM to be full graphics and rebooted.

**Comment by lamixer** [comment]
This happened to me installing aarch64 Fedora 37. If I started over and chose NOT to do disk encryption (when reinstalling Fedora from the iso) this problem did NOT happen.

**Comment by darchX** [comment]
I found the workaround and suitable solution for the issue related to the boot with the GUI.
I personally found the issue in Fedora 38 and Ubuntu 22.04.2 LTS (both ARM), but I strongly think that you may find it in every distro, certainly when using LUKS.

Below you find the procedure.

### Disable clipboard sharing
I believe it's optional, but that’s my setup at the moment.

<img width="794" alt="Screenshot 2023-05-08 at 12 44 06 AM" src="https://user-images.githubusercontent.com/92273556/236709651-e73a3fb7-cc2c-42dd-b087-c402b48cc26f.png">



### Display config

<img width="791" alt="Screenshot 2023-05-08 at 12 44 25 AM" src="https://user-images.githubusercontent.com/92273556/236709673-64641275-a94f-48cf-854a-a18bc30768f3.png">

### Add the serial device and leave the default config

<img width="789" alt="Screenshot 2023-05-08 at 12 44 33 AM" src="https://user-images.githubusercontent.com/92273556/236709683-eed53816-cbc9-4a7b-98d6-f43f211fc060.png">
 

### Remove the USB drive from the menu
It’s very well known that it can create issues with the boot process, but if you need it desperately, then put it below the boot disk drive.

<img width="788" alt="Screenshot 2023-05-08 at 12 44 43 AM" src="https://user-images.githubusercontent.com/92273556/236709734-7865e9c3-b6bb-4586-9262-48469d206170.png">


### Boot and insert the LUKS password
<img width="1381" alt="Screenshot 2023-05-08 at 12 41 59 AM" src="https://user-images.githubusercontent.com/92273556/236709740-f451e813-41a8-4efc-8202-8986bd5ae70e.png">
 

The terminal you see on the screen is the Serial Console that you added in UTM (so called “Serial”), after the UTM release 4.x.x, you need to add it manually, there isn’t anymore the option to select boot in “Console Only” mode instead of “Full Graphics”.
This terminal will remain open, I suggest leaving it in this way, in case of issues with the GUI, you’ll have access to perform basic troubleshooting and probably restart the GUI server, just to mention one.

Please note that you may not be able to see the prompt line when the password is requested by LUKS, give it a kick with a random “enter”, or insert the password directly, but this method shouldn’t be the preferred one because it may get logged if you are not at that password-entry step…

### Side notes

All the above has been tested with Fedora 38, but it should work in the same with any other distro out there.
At the given time, I wasn’t able to find the reason for the issue due to the missing logs for troubleshooting, looking at the stage of the failure, chances are with a GRUB missing entry for the display server config…

The OS installation doesn’t need anything as such, it should always work flawlessly even with the GUI, but you can try this workaround anyway, or simply install the server version with the terminal and the install the GUI, nowadays it’s quite intuitive, for example with Ubuntu is less than 20 obvious steps…

Overall, this doesn't seem to be an issue with UTM, but I think that this guide should end up in the official doc in order to make UTM usable to everyone.

**Comment by Drinkingpants74** [comment]
I was attempting the possible solution from @123andy and found another workaround and something interesting. I didn't turn off my display when I added the Serial connection and both ran together. Where the display gave me the "EFI Stub" errors I'd been seeing, the Serial console kept churning along. Eventually the Serial console stopped, and it asked me for my encryption password. I typed it in, hit enter, and Fedora booted right up.

Reading a few of these posts, this would explain why @lamixer was able to boot into Fedora 37 without the issue by not encrypting the drive (Didn't work for me however), and why @samuela noticed a 100% QEMU usage. I'm nowhere near qualified enough to understand what's causing this, but it feels like the display isn't updating, which isn't allowing me to type in my encryption password on boot. This gives the appearance of the VM crashing, when it actually hasn't, it's just waiting for input.

_(Ignore the fact that the VM title says (x64) in the images, it's an ARM VM, I'm just an idiot and didn't name it properly 🙃)_

**Before Encryption Password:**
<img width="1471" alt="Screenshot 2023-11-04 at 10 16 19 PM" src="https://github.com/utmapp/UTM/assets/60319968/92fe5451-5722-4de9-a217-1e857d5501bd">

**After Encryption Password:**
<img width="1654" alt="Screenshot 2023-11-04 at 10 17 34 PM" src="https://github.com/utmapp/UTM/assets/60319968/32147d9a-0b59-4f41-a3ad-c7f009391cb9">

**Comment by semtex41** [comment]
> I was attempting the possible solution from @123andy and found another workaround and something interesting. I didn't turn off my display when I added the Serial connection and both ran together. Where the display gave me the "EFI Stub" errors I'd been seeing, the Serial console kept churning along. Eventually the Serial console stopped, and it asked me for my encryption password. I typed it in, hit enter, and Fedora booted right up.
> 
> Reading a few of these posts, this would explain why @lamixer was able to boot into Fedora 37 without the issue by not encrypting the drive (Didn't work for me however), and why @samuela noticed a 100% QEMU usage. I'm nowhere near qualified enough to understand what's causing this, but it feels like the display isn't updating, which isn't allowing me to type in my encryption password on boot. This gives the appearance of the VM crashing, when it actually hasn't, it's just waiting for input.
> 
> _(Ignore the fact that the VM title says (x64) in the images, it's an ARM VM, I'm just an idiot and didn't name it properly 🙃)_
> 
> **Before Encryption Password:** <img alt="Screenshot 2023-11-04 at 10 16 19 PM" width="1471" src="https://user-images.githubusercontent.com/60319968/280502191-92fe5451-5722-4de9-a217-1e857d5501bd.png">
> 
> **After Encryption Password:** <img alt="Screenshot 2023-11-04 at 10 17 34 PM" width="1654" src="https://user-images.githubusercontent.com/60319968/280502229-32147d9a-0b59-4f41-a3ad-c7f009391cb9.png">

This is the way. I added a serial device, default settings, then when i started the ubuntu server 23.10 ARM VM, i was able to type the LUKS password and it worked. Bravo!
