### ISSUE TITLE
Pixel/Scroll Sensitivity Issue

### ISSUE THREAD

**Issue by gabrielipcarvalho** [utmapp/UTM#3417]
**Describe the issue**
Hi everyone! So I installed Debian (11), Ubuntu (20) and Windows (11) in my MacBook Air M1. All OSs are running fine, and they are all using the ARM64 architecture.

But there is a common issue I'm facing in all three guests: there must be some problem for the UTM to send over the mouse/trackpad scrolling inputs to the guests OSs. In sum, while in any of these guests, I have to slide my fingers in the built in trackpad for some distance before the page (be it a system page or any app) "jumps" either down or up, left or right. I then tried out using my Magic Mouse, same issue... I also have a regular bluetooth mouse with the traditional wheel on it. When I connected it, I could assert having to scroll about 10-12 wheel "clicks" for the guest system to input what should be one wheel "click".

I have had the same issue once with VMWare Fusion, in there I could fix the issue adding these bellow lines in the .vmx file of each guest OS:

```
mouse.vusb.enable = "TRUE"
mouse.vusb.useBasicMouse = "FALSE"
mks.mouse.pixelScrollSensitivity = "1"
```

I tried searching online for some solution on UTM, but haven't had any luck so far, the closest I got was this thread [https://github.com/utmapp/UTM/issues/2400](url), but it didn't quite addresses my issues here.

**Configuration**
* UTM Version: 2.4.1 (40)
* OS Version: macOs Monterey 12.0.1 (host)
* Intel or Apple Silicon? Apple Silicon

**Crash log**
Haven't had any crashes.

**Debug log**
I'm not really sure if this log is going to help, basically I just enabled Debug Log in my Debian VM, turned it on, opened Firefox, scrolled down a bit, verified the occurrence of the issue, powered off the VM and exported the log, it follows bellow:  

```
Running:  -L /Applications/UTM.app/Contents/Resources/qemu -S -qmp tcp:127.0.0.1:4000,server,nowait -nodefaults -vga none -spice "unix=on,addr=/Users/gabriel/Library/Group Containers/WDNLXAD4W8.com.utmapp.UTM/E69A7C1C-F7ED-4EC2-89C0-D1C735D9509B.spice,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=on" -device virtio-ramfb-gl -cpu cortex-a72 -smp cpus=4,sockets=1,cores=4,threads=1 -machine virt,highmem=off -accel hvf -accel tcg,thread=multi,tb-size=1024 -drive if=pflash,format=raw,unit=0,file=/Applications/UTM.app/Contents/Resources/qemu/edk2-aarch64-code.fd,readonly=on -drive if=pflash,format=raw,unit=1,file=/Users/gabriel/Library/Containers/com.utmapp.UTM/Data/Documents/Debian.utm/Images/efi_vars.fd -boot menu=on -m 4096 -device intel-hda -device hda-duplex -name Debian -device qemu-xhci,id=usb-bus -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device ich9-usb-ehci1,id=usb-controller-0 -device ich9-usb-uhci1,masterbus=usb-controller-0.0,firstport=0,multifunction=on -device ich9-usb-uhci2,masterbus=usb-controller-0.0,firstport=2,multifunction=on -device ich9-usb-uhci3,masterbus=usb-controller-0.0,firstport=4,multifunction=on -chardev spicevmc,name=usbredir,id=usbredirchardev0 -device usb-redir,chardev=usbredirchardev0,id=usbredirdev0,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,bus=usb-controller-0.0 -device nvme,drive=drive0,serial=drive0,bootindex=0 -drive if=none,media=disk,id=drive0,file=/Users/gabriel/Library/Containers/com.utmapp.UTM/Data/Documents/Debian.utm/Images/disk-0.qcow2,cache=writethrough -device usb-storage,drive=drive1,removable=true,bootindex=1,bus=usb-bus.0 -drive if=none,media=cdrom,id=drive1 -device virtio-net-pci,mac=8A:08:55:F6:6C:B5,netdev=net0 -netdev vmnet-macos,mode=shared,id=net0 -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -device virtserialport,chardev=charchannel1,id=channel1,name=org.spice-space.webdav.0 -chardev spiceport,name=org.spice-space.webdav.0,id=charchannel1 -uuid E69A7C1C-F7ED-4EC2-89C0-D1C735D9509B -rtc base=localtime
qemu-aarch64-softmmu: -netdev vmnet-macos,mode=shared,id=net0: info: Started vmnet interface with configuration:
qemu-aarch64-softmmu: -netdev vmnet-macos,mode=shared,id=net0: info: MTU:              1500
qemu-aarch64-softmmu: -netdev vmnet-macos,mode=shared,id=net0: info: Max packet size:  1514
qemu-aarch64-softmmu: -netdev vmnet-macos,mode=shared,id=net0: info: MAC:              4a:34:43:ca:d5:39
qemu-aarch64-softmmu: -netdev vmnet-macos,mode=shared,id=net0: info: DHCP IPv4 start:  192.168.64.1
qemu-aarch64-softmmu: -netdev vmnet-macos,mode=shared,id=net0: info: DHCP IPv4 end:    192.168.64.254
qemu-aarch64-softmmu: -netdev vmnet-macos,mode=shared,id=net0: info: IPv4 subnet mask: 255.255.255.0
qemu-aarch64-softmmu: -netdev vmnet-macos,mode=shared,id=net0: info: UUID:             1AF6D5C3-23C9-497E-8B53-DC7EC3B18240
qemu-aarch64-softmmu: warning: Spice: playback:0 (0x1558d0120): setsockopt failed, Operation not supported on socket
qemu-aarch64-softmmu: warning: Spice: record:0 (0x1558d01d0): setsockopt failed, Operation not supported on socket
gl_version 30 - es profile enabled
WARNING: running without ARB/KHR robustness in place may crash
vrend_renderer_fill_caps: Entering with stale GL error: 1280
GLSL feature level 130
```

**Upload VM**
I'll be attaching bellow the config.plist of all my guest OSs 

Debian 11:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ConfigurationVersion</key>
	<integer>2</integer>
	<key>Debug</key>
	<dict>
		<key>DebugLog</key>
		<false/>
		<key>IgnoreAllConfiguration</key>
		<false/>
	</dict>
	<key>Display</key>
	<dict>
		<key>ConsoleFont</key>
		<string>Menlo</string>
		<key>ConsoleFontSize</key>
		<integer>12</integer>
		<key>ConsoleOnly</key>
		<false/>
		<key>ConsoleTheme</key>
		<string>Default</string>
		<key>DisplayCard</key>
		<string>virtio-ramfb-gl</string>
		<key>DisplayDownscaler</key>
		<string>linear</string>
		<key>DisplayFitScreen</key>
		<true/>
		<key>DisplayRetina</key>
		<false/>
		<key>DisplayUpscaler</key>
		<string>linear</string>
	</dict>
	<key>Drives</key>
	<array>
		<dict>
			<key>DriveName</key>
			<string>drive0</string>
			<key>ImagePath</key>
			<string>disk-0.qcow2</string>
			<key>ImageType</key>
			<string>disk</string>
			<key>InterfaceType</key>
			<string>nvme</string>
		</dict>
		<dict>
			<key>DriveName</key>
			<string>drive1</string>
			<key>ImageType</key>
			<string>cd</string>
			<key>InterfaceType</key>
			<string>usb</string>
			<key>Removable</key>
			<true/>
		</dict>
		<dict>
			<key>DriveName</key>
			<string>408A57DB-5FC0-47A1-B8C4-1B6FFAD9AE34</string>
			<key>ImagePath</key>
			<string>efi_vars.fd</string>
			<key>ImageType</key>
			<string>none</string>
			<key>InterfaceType</key>
			<string></string>
		</dict>
	</array>
	<key>Info</key>
	<dict>
		<key>Icon</key>
		<string>debian</string>
		<key>IconCustom</key>
		<false/>
	</dict>
	<key>Input</key>
	<dict>
		<key>InputLegacy</key>
		<false/>
	</dict>
	<key>Networking</key>
	<dict>
		<key>NetworkCard</key>
		<string>virtio-net-pci</string>
		<key>NetworkCardMAC</key>
		<string>8A:08:55:F6:6C:B5</string>
		<key>NetworkMode</key>
		<string>shared</string>
	</dict>
	<key>Printing</key>
	<dict/>
	<key>Sharing</key>
	<dict>
		<key>ClipboardSharing</key>
		<true/>
		<key>DirectorySharing</key>
		<true/>
		<key>Usb3Support</key>
		<false/>
		<key>UsbRedirectMax</key>
		<integer>3</integer>
	</dict>
	<key>Sound</key>
	<dict>
		<key>SoundCard</key>
		<string>intel-hda</string>
		<key>SoundEnabled</key>
		<true/>
	</dict>
	<key>System</key>
	<dict>
		<key>AddArgs</key>
		<array>
			<string></string>
		</array>
		<key>Architecture</key>
		<string>aarch64</string>
		<key>BootDevice</key>
		<string></string>
		<key>BootUefi</key>
		<true/>
		<key>CPU</key>
		<string>cortex-a72</string>
		<key>CPUCount</key>
		<integer>4</integer>
		<key>ForceMulticore</key>
		<true/>
		<key>JITCacheSize</key>
		<integer>0</integer>
		<key>MachineProperties</key>
		<string>highmem=off</string>
		<key>Memory</key>
		<integer>4096</integer>
		<key>SystemUUID</key>
		<string>E69A7C1C-F7ED-4EC2-89C0-D1C735D9509B</string>
		<key>Target</key>
		<string>virt</string>
	</dict>
</dict>
</plist>
```

Ubuntu 20:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ConfigurationVersion</key>
	<integer>2</integer>
	<key>Debug</key>
	<dict/>
	<key>Display</key>
	<dict>
		<key>ConsoleFont</key>
		<string>Menlo</string>
		<key>ConsoleFontSize</key>
		<integer>12</integer>
		<key>ConsoleOnly</key>
		<false/>
		<key>ConsoleTheme</key>
		<string>Default</string>
		<key>DisplayCard</key>
		<string>virtio-ramfb-gl</string>
		<key>DisplayDownscaler</key>
		<string>linear</string>
		<key>DisplayFitScreen</key>
		<true/>
		<key>DisplayUpscaler</key>
		<string>linear</string>
	</dict>
	<key>Drives</key>
	<array>
		<dict>
			<key>DriveName</key>
			<string>drive0</string>
			<key>ImagePath</key>
			<string>disk-0.qcow2</string>
			<key>ImageType</key>
			<string>disk</string>
			<key>InterfaceType</key>
			<string>nvme</string>
		</dict>
		<dict>
			<key>DriveName</key>
			<string>drive1</string>
			<key>ImageType</key>
			<string>cd</string>
			<key>InterfaceType</key>
			<string>usb</string>
			<key>Removable</key>
			<true/>
		</dict>
		<dict>
			<key>DriveName</key>
			<string>EEED43A1-440B-4977-BFDE-C15863D644C1</string>
			<key>ImagePath</key>
			<string>efi_vars.fd</string>
			<key>ImageType</key>
			<string>none</string>
			<key>InterfaceType</key>
			<string></string>
		</dict>
	</array>
	<key>Info</key>
	<dict>
		<key>Icon</key>
		<string>ubuntu</string>
		<key>IconCustom</key>
		<false/>
	</dict>
	<key>Input</key>
	<dict>
		<key>InputInvertScroll</key>
		<false/>
		<key>InputLegacy</key>
		<false/>
	</dict>
	<key>Networking</key>
	<dict>
		<key>NetworkCard</key>
		<string>virtio-net-pci</string>
		<key>NetworkCardMAC</key>
		<string>6E:8A:11:ED:84:C9</string>
		<key>NetworkMode</key>
		<string>shared</string>
	</dict>
	<key>Printing</key>
	<dict/>
	<key>Sharing</key>
	<dict>
		<key>ClipboardSharing</key>
		<true/>
		<key>DirectorySharing</key>
		<true/>
		<key>Usb3Support</key>
		<false/>
		<key>UsbRedirectMax</key>
		<integer>3</integer>
	</dict>
	<key>Sound</key>
	<dict>
		<key>SoundCard</key>
		<string>intel-hda</string>
		<key>SoundEnabled</key>
		<true/>
	</dict>
	<key>System</key>
	<dict>
		<key>Architecture</key>
		<string>aarch64</string>
		<key>BootDevice</key>
		<string></string>
		<key>BootUefi</key>
		<true/>
		<key>CPU</key>
		<string>cortex-a72</string>
		<key>CPUCount</key>
		<integer>4</integer>
		<key>ForceMulticore</key>
		<true/>
		<key>JITCacheSize</key>
		<integer>0</integer>
		<key>MachineProperties</key>
		<string>highmem=off</string>
		<key>Memory</key>
		<integer>4096</integer>
		<key>SystemUUID</key>
		<string>9F3B496B-D294-44FC-AADF-5FDC736BB1FC</string>
		<key>Target</key>
		<string>virt</string>
	</dict>
</dict>
</plist>
```

Windows 11:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ConfigurationVersion</key>
	<integer>2</integer>
	<key>Debug</key>
	<dict/>
	<key>Display</key>
	<dict>
		<key>ConsoleFont</key>
		<string>Menlo</string>
		<key>ConsoleFontSize</key>
		<integer>12</integer>
		<key>ConsoleOnly</key>
		<false/>
		<key>ConsoleTheme</key>
		<string>Default</string>
		<key>DisplayCard</key>
		<string>virtio-ramfb-gl</string>
		<key>DisplayDownscaler</key>
		<string>linear</string>
		<key>DisplayFitScreen</key>
		<true/>
		<key>DisplayRetina</key>
		<false/>
		<key>DisplayUpscaler</key>
		<string>linear</string>
	</dict>
	<key>Drives</key>
	<array>
		<dict>
			<key>DriveName</key>
			<string>drive0</string>
			<key>ImagePath</key>
			<string>disk-0.qcow2</string>
			<key>ImageType</key>
			<string>disk</string>
			<key>InterfaceType</key>
			<string>nvme</string>
		</dict>
		<dict>
			<key>DriveName</key>
			<string>drive1</string>
			<key>ImageType</key>
			<string>cd</string>
			<key>InterfaceType</key>
			<string>none</string>
			<key>Removable</key>
			<true/>
		</dict>
		<dict>
			<key>DriveName</key>
			<string>7B3E7C43-91B4-4CCB-97F1-52656B41D524</string>
			<key>ImagePath</key>
			<string>efi_vars.fd</string>
			<key>ImageType</key>
			<string>none</string>
			<key>InterfaceType</key>
			<string></string>
		</dict>
	</array>
	<key>Info</key>
	<dict>
		<key>Icon</key>
		<string>windows</string>
		<key>IconCustom</key>
		<false/>
	</dict>
	<key>Input</key>
	<dict>
		<key>InputInvertScroll</key>
		<true/>
		<key>InputLegacy</key>
		<false/>
	</dict>
	<key>Networking</key>
	<dict>
		<key>NetworkCard</key>
		<string>virtio-net-pci</string>
		<key>NetworkCardMAC</key>
		<string>EA:0B:EA:66:FF:A4</string>
		<key>NetworkMode</key>
		<string>shared</string>
	</dict>
	<key>Printing</key>
	<dict/>
	<key>Sharing</key>
	<dict>
		<key>ClipboardSharing</key>
		<true/>
		<key>DirectorySharing</key>
		<true/>
		<key>Usb3Support</key>
		<false/>
		<key>UsbRedirectMax</key>
		<integer>3</integer>
	</dict>
	<key>Sound</key>
	<dict>
		<key>SoundCard</key>
		<string>intel-hda</string>
		<key>SoundEnabled</key>
		<true/>
	</dict>
	<key>System</key>
	<dict>
		<key>AddArgs</key>
		<array>
			<string>-device</string>
			<string>usb-storage,drive=drive1,removable=true,bootindex=1,bus=usb-bus.0</string>
		</array>
		<key>Architecture</key>
		<string>aarch64</string>
		<key>BootDevice</key>
		<string></string>
		<key>BootUefi</key>
		<true/>
		<key>CPU</key>
		<string>default</string>
		<key>CPUCount</key>
		<integer>4</integer>
		<key>ForceMulticore</key>
		<true/>
		<key>JITCacheSize</key>
		<integer>0</integer>
		<key>MachineProperties</key>
		<string>highmem=off,virtualization=on</string>
		<key>Memory</key>
		<integer>4096</integer>
		<key>SystemUUID</key>
		<string>751BB571-C919-4740-ADF6-EDB49785B02D</string>
		<key>Target</key>
		<string>virt</string>
	</dict>
</dict>
</plist>
```

**Comment by conath** [comment]
I can not reproduce this on my M1 MacBook Pro running UTM 2.4.1 and macOS 12.1.

In a Windows 8.1 VM, scrolling is slightly jumpy when using the Trackpad, but it might just be general system lag from emulation.

In a Ubuntu 21.04 ARM VM with Ubuntu Desktop installed, scrolling works perfectly fine. 

On both systems I installed the [appropriate guest tools](https://mac.getutm.app/support/).

**Comment by gabrielipcarvalho** [comment]
Thanks!

I have the guest tools installed in all three guests too. 

Considering it is a very isolated issue, I'm guessing there might be an app installed in my machine which could be messing/controlling the mouse/trackpad scrolling inputs, while macOS might not have a problem with it, UTM might be understanding the inputs differently. 

I have an intel MacBook Pro 2017, I'll be testing the scrolling behavior there and I'll report back here!

**Comment by bradsevy** [comment]
I also have the same problem. Ubuntu 21.10 arm, Debian 11 and Testing arm. This is occurring on MacBook Air M1 on macoS 12.1.

**Comment by vincent-olivert-riera** [comment]
Same problem here. MacOS arm64 as host, Debian arm64 as guest.
The mouse wheel is not very responsive and I need to do multiple "clicks" fast to make it work. On the host OS (Mac), I can spin the mouse wheel very slowly (one "click" every 5 seconds, for instance), and it reacts on every single one. However, doing that on the guest OS (Debian), all the "clicks" are just ignored.
It seems that it needs a certain quantity of mouse wheel "clicks" per unit of time in order to react and actually perform a scroll action.

**Comment by szymek116** [comment]
same thing for me, is there an option to modify qemu params in UTM to experiment whether any of them causes this effect ? I saw I can add them and tried few things around msmouse protocol but without effect. I checked the same on VMware virtualzation and there mouse works correctly (the same M1 box). I tried to run pure qemu to see whether it will be reproducible there but no luck yet (I am starting to discover why we need things like UTM to work with it :D)

**Comment by vincent-olivert-riera** [comment]
> Same problem here. MacOS arm64 as host, Debian arm64 as guest. The mouse wheel is not very responsive and I need to do multiple "clicks" fast to make it work. On the host OS (Mac), I can spin the mouse wheel very slowly (one "click" every 5 seconds, for instance), and it reacts on every single one. However, doing that on the guest OS (Debian), all the "clicks" are just ignored. It seems that it needs a certain quantity of mouse wheel "clicks" per unit of time in order to react and actually perform a scroll action.
> 
> Tested with both the MacBook Pro M1 trackpad and a USB mouse.
> 
> > In a Ubuntu 21.04 ARM VM with Ubuntu Desktop installed, scrolling works perfectly fine.
> 
> @conath , really? So if you spin your mouse wheel slowly, one "click" at a time, like I described above, does Ubuntu react on every single "click"?

For the record, exactly the same happens when using Apple Virtualization.

**Comment by JeffSweeting** [comment]
For the record I'm having the same issue too. Brand new M2 MacBook Pro. Latest UTM running latest Debian 12 RISC version with XFCE. UTM Guest tools installed. You have to scroll the mouse scroll wheel 'rapidly' before it registers and scrolls the page in any Debian app.  Other than that the virtual machine is blazing fast. Mouse scroll wheel works great in native OSX.

**Comment by vincent-olivert-riera** [comment]
> For the record I'm having the same issue too. Brand new M2 MacBook Pro. Latest UTM running latest Debian 12 RISC version with XFCE. UTM Guest tools installed. You have to scroll the mouse scroll wheel 'rapidly' before it registers and scrolls the page in any Debian app. Other than that the virtual machine is blazing fast. Mouse scroll wheel works great in native OSX.

Check this comment https://github.com/utmapp/UTM/issues/5124#issuecomment-1501901886
And the one above it on the same issue. You may find it interesting. Since I started using qemu directly I don't have that mouse scroll issue.

**Comment by porjo** [comment]
Same issue here:
- UTM 4.4.4
- MacBook Pro 2019
- Fedora Linux VM

**Comment by Sijiahui** [comment]
Check this comment https://github.com/utmapp/UTM/issues/5693
This issue is caused by spice driver and occurs when using a Bluetooth mouse. The scroll wheel works fine when using a wired device.

**Comment by vincent-olivert-riera** [comment]
> Check this comment https://github.com/utmapp/UTM/issues/5693
> This issue is caused by spice driver and occurs when using a Bluetooth mouse. The scroll wheel works fine when using a wired device.

I don't think that's correct. I was using a wired mouse when I experienced that issue. I do not own any bluetooth mouse.

**Comment by sokurenko** [comment]
I have same issue

**Comment by j3ko** [comment]
Not a fix for the underlying issue, but if you're on linux using Firefox or a Chrome variant you can lower the sensitivity for just the browser:

https://askubuntu.com/a/1458258
https://askubuntu.com/a/1432270

At the very least you're browser isn't teleporting you pages at a time while you search for a permanent fix.

**Comment by hotdogthemovie** [comment]
I have been using UTM for over year, MBP M2 and Mac Mini M2 hosting Ubuntu 22.04 and now 24.04 vms.  Bluetooth mice work fine in Mac OS, but there is an annoying scroll wheel lag in the vms.  I have not experienced lag with mouse movement, only with scroll wheel movement.

**Comment by cristianadam** [comment]
I'm having the same issue with a Logi bluetooth mouse on a Macbook Pro M1 Max. I'm using Windows 11 / Ubuntu 22.04 and I haven't found a way to make scrolling not scroll too much.

I've set scrolling on Windows 11 to 1 line, didn't help.

**Comment by cristianadam** [comment]
> I'm having the same issue with a Logi bluetooth mouse on a Macbook Pro M1 Max. I'm using Windows 11 / Ubuntu 22.04 and I haven't found a way to make scrolling not scroll too much.
> 
> I've set scrolling on Windows 11 to 1 line, didn't help.

I've added to [MOS](https://mos.caldis.me/) a custom setting for UTM: minimum step and duration for scrolling. Now I can use the mouse on Windows! 🎉

**Comment by bcostdolby** [comment]
Finding the same issue using a basic usb mouse on the m3. However using the magic mouse, seems better (though there are no wheel "ticks"). 

I.e. The normal mouse, a single tick of mouse wheel doesn't move terminal scrolling in the VM at all but then more velocity on the wheel does. There is nothing and then there is a massive movement. 

I am going to look into tools like:
https://github.com/emreyolcu/discrete-scroll

Or the MOS one above. I have tried a few ideas from:
https://apple.stackexchange.com/questions/253111/how-to-disable-scroll-acceleration-in-macos-sierra

Could this be that macos is doing some interpretation of the mouse wheel to apply some form of acceleration/inertia, and then ubuntu is then doing the same so its applying the acceleration logic twice for the wheel?

**Comment by mvysny** [comment]
I can also reproduce the issue. Finally found https://linearmouse.app which helped, but it reconfigured the mouse scrolling behavior for the entire MacOS, which may not be what you want.

To reproduce this bug:
1. Plug in an USB Microsoft Mouse to your MacBook
2. Start Ubuntu in UTM
3. Open Firefox in Ubuntu/UTM and open any web page.
4. Scroll with one "wheel click" and observe that nothing is scrolled in Firefox/Ubuntu/UTM

The reason for that is that MacBook uses scroll acceleration by default: one wheel click emits a very small value while multitude of wheel clicks in succession emits a higher scrolling value which finally gets registered by Linux/UTM.

Workaround is to install https://linearmouse.app . Then:

1. Set "Scrolling" / "Scrolling mode" to "By Lines"
2. Set "Distance" to 3 or more.

Observation: LinearMouse needs to obtain the Accessibility permission, in "System Settings"/"Privacy & Security"/"Accessibility". I noticed that Parallels did the very same thing. The mouse scrolling works very well in Parallels - the hypothesis is that Parallels obtains the accessibility permission and then reconfigures the scroll acceleration for Parallels windows... but this is pure speculation.

**Comment by keithbuel** [comment]
Have the same problem with current configuration

- UTM 4.6.4
- Mac OS: Sequoia 15.2
- Chipset: M1 Pro
- VM: Ubuntu  24.04

 
> Workaround is to install https://linearmouse.app . Then:
> 
> 1. Set "Scrolling" / "Scrolling mode" to "By Lines"
> 2. Set "Distance" to 3 or more.

Confirmed this worked for me.

**Comment by XuPengfei-1020** [comment]
Same problem here.
UTM: 4.6.5
Host: mac-mini m4chip, 16G.
VM: macos 15, 8G.

**Comment by erikbuh** [comment]
Same issue, but just with the Macbook Trackpad. The scrolling was not working well on:
UTM: 4.6.5
Host: M1 Mac OS 15.6
Guest: Mac OS 15.6

> Workaround is to install [https://linearmouse.app/](https://linearmouse.app/).

Thanks! This worked for me somehow. Just by installing it and leaving the default trackpad configuration. Now the problem is resolved.

**Comment by paulsc** [comment]
I had the same issue.

UTM 4.7.4.
MacOS 15.6.1.
Guest: Ubuntu

> Workaround is to install https://linearmouse.app . Then:
> 
>     1. Set "Scrolling" / "Scrolling mode" to "By Lines"
> 
>     2. Set "Distance" to 3 or more. 

This fix also worked for me.

I have the Logitech MX Anywhere 2S which where the hardware has both "click-mode" and "smooth-mode" for the wheel, you can press the wheel on the mouse to switch between those modes. I found that in click mode, even with Distance set to 10, it would miss a "click" event every now and then. It works ok for now in "smooth-mode".

Thanks

**Comment by michaelerule** [comment]
paulsc's fix partially worked for me, but in a way that hints of some remaining underlying bug. I'm on macos 14.4, URM 4.6.5 (108), and testing in Linux debian 6.1.0-32-arm64. I copied paulsc's fix, except that I found that I needed to set the "distance" in scroll lines to 1 rather than 3. 

The end result still isn't quite functional: I'm using a wireless logitech USB mouse, and on the host macos one click of the scroll wheel will move the browser 1 line. On the client Debian, one click of the scroll wheel will stochastically either do nothing, or move 3 lines. But, this is better than the earlier behaviour of multiple clicks doing nothing.

**Comment by Stronautt** [comment]
For the choppy, too-fast scrolling in a Linux guest, there's a small daemon that handles it: https://github.com/stronautt/smooth-scroll-daemon

It runs at the evdev layer (works on `X11` and `Wayland`, any DE) and re-emits the scroll events with a non-linear curve plus inertia, instead of a flat multiplier. So slow scrolling stays precise, and fast flicks don't fly off the screen. Defaults are set up for a MacBook **trackpad** under **UTM**, and the `curve`, `friction`, and `multiplier` are all flags you can adjust.

Single C file, only needs `libevdev`. Worked for my Ubuntu guest, might be useful here.
