### ISSUE TITLE
macOS Guest - App Store/iCloud Login Failure

### ISSUE THREAD

**Issue by tjbx** [utmapp/UTM#3617]
**Describe the issue**
I have a macOS guest (12.2.1) that works amazingly well with one strange issue - I am unable to log into iCloud nor the App Store. Both fail with the helpful error message "The action could not be completed." 

**Configuration**
* UTM Version: 3.0.4
* OS Version: 12.2.1
* Intel or Apple Silicon? M1 Mac mini

**Comment by zuzzurro** [comment]
Exact same error here (I only tried the App Store).

**Comment by osy** [comment]
This is an intentional limitation from Apple in their Virtualization APIs.

**Comment by zuzzurro** [comment]
Can you please give a URL pointing out where it's documented and how to work around it? Thanks..

**Comment by osy** [comment]
There's no documentation or workaround. This is from conversations with Apple.

**Comment by zuzzurro** [comment]
Thanks, sorry for being dense. Does it mean that NO id whatsoever can be used inside a VM? Or that one should use a special one different from the one used in the guest?
It means that no app can be downloaded from the Apple Store, does it? If I want to install an app I need to get the package directly.

**Comment by natevw** [comment]
Just a bystander here, but for anyone else following along at home:

I wonder if this is related to the longstanding device model/serno limitations on Apple ID usage from VMs (e.g. https://github.com/myspaghetti/macos-virtualbox#icloud-and-imessage-connectivity-and-nvram). Perhaps the Virtualization framework doesn't even support overriding the configuration of those underlying identifiers?

**Comment by mattruzzi** [comment]
https://kb.parallels.com/128867
https://forum.parallels.com/threads/apple-id-login-in-macos-guest-os.355059/
https://developer.apple.com/forums/thread/707682

**Comment by paulocoutinhox** [comment]
If we run in x86_64 using Rosetta, it works?

**Comment by paulocoutinhox** [comment]
It was solved?

**Comment by mattruzzi** [comment]
Using iCloud with macOS virtual machines
https://developer.apple.com/documentation/virtualization/using_icloud_with_macos_virtual_machines

**Comment by jaltman** [comment]
> Using iCloud with macOS virtual machines https://developer.apple.com/documentation/virtualization/using_icloud_with_macos_virtual_machines

Although iCloud can be used within a new macOS 15 VM there are still restrictions on logging into the App Store from a VM.

**Comment by ds-ep** [comment]
Maybe i am missing something but it still does not seem to work. Host on 15.0.1 and guest on a newly created 15.0.1

**Comment by yasvue** [comment]
any solution to this? latest UTM with latest macOS, still can't login in appstore/icloud

**Comment by szymczag** [comment]
The same in July 2025.

<img width="285" height="233" alt="Image" src="https://github.com/user-attachments/assets/44725e64-a343-4497-91db-e63bd23a5098" />

(and in the meantime I'm getting a prompt on iOS to confirm - which normally works just fine).

macOS 15.6 (24G84), UTM Version 4.6.5 (108).

**Comment by weiweihuanghuang** [comment]
How do I install applications from app store if I can't log into to Apple ID?
