### ISSUE TITLE
No UTM Folder in Files App

### ISSUE THREAD

**Issue by snslpa** [utmapp/UTM#362]
Hi, since I installed the latest UTM version rc4, there is no UTM folder in my Files App.

**Comment by osy86** [comment]
This has been fixed in https://github.com/utmapp/UTM/commit/d5da9970517270a1fa305a7777ec16a0f50d2753

**Comment by Nanoc-ice** [comment]
I see that you fixed this for rc5, in the meantime is there any suggested work around?  I created a UTM folder manually, deleted and re-added UTM and it doesn’t see the one manually created.  I am also, installing the app via Xcode, if that matters.

**Comment by osy86** [comment]
You can use iTunes

**Comment by Nanoc-ice** [comment]
Thanks for the quick response, but still no luck UTM finding/creating a UTM folder.  In OS X Catalina, the iTunes functionality has been split amount several apps.  So, using the old iTunes method didn’t have an impact for installation and the document folder.

**Comment by Nanoc-ice** [comment]
I cloned, built and signed locally and am back working again.

**Comment by osy86** [comment]
I will try to release RC5 quickly this time to fix this.
