### ISSUE TITLE
USB device not recognized

### ISSUE THREAD

**Issue by zwb124** [utmapp/UTM#3975]
utm 3.2.1 cannot recognize any USB devices in vm

**Configuration**
* UTM Version: 3.2.1
* OS Version: macOS 12.3.1
* Apple Silicon,macbook 14

**Comment by freebrowser1** [comment]
Here (using UTM 3.1.5, same macOS M1 version), a USB stick is recognized, but an external harddisk (the small blue Samsung T7 2TB) formatted to exFAT is not recognized.

**Comment by Kexkey** [comment]
Same here.  When playing with `Input` configs, `USB Support` and number of USB Devices, I can sometimes get my USB stick to be available from within the VM but then networking/Internet doesn't work.  When removing USB support, networking is available again.  I unfortunately couldn't find a pattern for this, I tried a lot of different combinations.  So when I need to access the data on my USB storage, I make sure I don't need net access, copy my stuff and then restart the VM without USB and can go on.

More details: M1.  Debian VM.  Using `sudo lsblk` to list devices.  Simply `sudo apt update` to test networking.  When networking is down, I can't ssh @localhost (makes sense), I need to use VM console.  Can't ping IP addresses either, getting `Network is unreachable`.

**Comment by SmartBoy84** [comment]
I'm having the same issue on my device

**Comment by osy** [comment]
@zwb124 Is this issue new to 3.2.1? Can the same device be recognized in 3.1.5?

**Comment by zwb124** [comment]
> @zwb124 Is this issue new to 3.2.1? Can the same device be recognized in 3.1.5?

yes，3.2.1，it seems good in 3.1.5，I don't remember.

**Comment by osy** [comment]
@zwb124 Is your device USB 3.0 and did you enable USB 3.0?

<img width="816" alt="image" src="https://user-images.githubusercontent.com/50960678/167226426-b8de5304-3e94-40e7-b998-cfd5a80fef1e.png">

**Comment by zwb124** [comment]
> @zwb124 Is your device USB 3.0 and did you enable USB 3.0?
> 
> <img alt="image" width="816" src="https://user-images.githubusercontent.com/50960678/167226426-b8de5304-3e94-40e7-b998-cfd5a80fef1e.png">

yes，it is enable

**Comment by osy** [comment]
Do you get any error message? Can you enable logging in QEMU settings and provide the log?

**Comment by zwb124** [comment]
No,There are no error messages,The VM did not respond when the USB device was plugged in

Here is the log：
Running:  -L /Applications/UTM.app/Contents/Resources/qemu -S -qmp tcp:127.0.0.1:4000,server,nowait -nodefaults -vga none -spice "unix=on,addr=/Users/zhouwenbo/Library/Group Containers/WDNLXAD4W8.com.utmapp.UTM/2BCCA292-D7D6-469E-922D-CB6CFBEDC04C.spice,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=off" -device virtio-ramfb -cpu host -smp cpus=4,sockets=1,cores=4,threads=1 -machine virt,highmem=off -accel hvf -accel tcg,tb-size=1024 -drive if=pflash,format=raw,unit=0,file=/Applications/UTM.app/Contents/Resources/qemu/edk2-aarch64-code.fd,readonly=on -drive if=pflash,unit=1,file=/Users/zhouwenbo/Library/Containers/com.utmapp.UTM/Data/Documents/Windows11.utm/Images/efi_vars.fd -boot menu=on -m 4096 -device intel-hda -device hda-duplex -name Windows11 -device nec-usb-xhci,id=usb-bus -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device qemu-xhci,id=usb-controller-0 -chardev spicevmc,name=usbredir,id=usbredirchardev0 -device usb-redir,chardev=usbredirchardev0,id=usbredirdev0,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,bus=usb-controller-0.0 -device usb-storage,drive=cdrom0,removable=true,bootindex=0,bus=usb-bus.0 -drive if=none,media=cdrom,id=cdrom0 -device nvme,drive=drive0,serial=drive0,bootindex=1 -drive if=none,media=disk,id=drive0,file=/Users/zhouwenbo/Library/Containers/com.utmapp.UTM/Data/Documents/Windows11.utm/Images/data.qcow2,discard=unmap,detect-zeroes=unmap -device virtio-net-pci,mac=DA:6E:A0:A5:6F:B5,netdev=net0 -netdev vmnet-shared,id=net0 -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -device virtserialport,chardev=charchannel1,id=channel1,name=org.spice-space.webdav.0 -chardev spiceport,name=org.spice-space.webdav.0,id=charchannel1 -uuid 2BCCA292-D7D6-469E-922D-CB6CFBEDC04C -rtc base=localtime -device virtio-rng-pci
WARNING: Image format was not specified for '/Users/zhouwenbo/Library/Containers/com.utmapp.UTM/Data/Documents/Windows11.utm/Images/efi_vars.fd' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
qemu-aarch64-softmmu: warning: Spice: playback:0 (0x12d08f140): setsockopt failed, Operation not supported on socket
qemu-aarch64-softmmu: warning: Spice: record:0 (0x12d08f1e0): setsockopt failed, Operation not supported on socket
qemu-aarch64-softmmu: warning: vmnet: packet is too big, 0 > 1514
qemu-aarch64-softmmu: warning: vmnet: packet is too big, 0 > 1514
qemu-aarch64-softmmu: warning: vmnet: packet is too big, 0 > 1514
qemu-aarch64-softmmu: warning: vmnet: packet is too big, 0 > 1514
qemu-aarch64-softmmu: warning: vmnet: packet is too big, 0 > 1514
qemu-aarch64-softmmu: warning: vmnet: packet is too big, 0 > 1514
qemu-aarch64-softmmu: warning: vmnet: packet is too big, 0 > 1514
qemu-aarch64-softmmu: warning: vmnet: packet is too big, 0 > 1514
qemu-aarch64-softmmu: warning: vmnet: packet is too big, 0 > 1514
qemu-aarch64-softmmu: warning: vmnet: packet is too big, 0 > 1514
qemu-aarch64-softmmu: warning: vmnet: packet is too big, 0 > 1514
qemu-aarch64-softmmu: warning: vmnet: packet is too big, 0 > 1514

**Comment by osy** [comment]
You got the pop up when you plugged it in and the second pop up to allow attaching of the usb?

**Comment by zwb124** [comment]
> You got the pop up when you plugged it in and the second pop up to allow attaching of the usb?

no pop up

[https://github.com/zwb124/tempfile/blob/main/output.mp4?raw=true](url)

**Comment by osy** [comment]
I can't seem to access that. Is it hosted in a private repo? Anyways are you saying you were able to see the popup on 3.1.5 but on 3.2.1 there is no popup?

**Comment by zwb124** [comment]
> I can't seem to access that. Is it hosted in a private repo? Anyways are you saying you were able to see the popup on 3.1.5 but on 3.2.1 there is no popup?

yes，it is

**Comment by osy** [comment]
Can you reupload the video so it is not private?

**Comment by zwb124** [comment]
I changed it to public

**Comment by osy** [comment]
Thank you.

If you remove the drive from your computer. Then, while UTM is in the foreground, plug in the USB drive again. Do you see a prompt from UTM asking if you want to attach the drive?

**Comment by osy** [comment]
Another thing: did you download the release from https://github.com/utmapp/UTM/releases or from TestFlight.

**Comment by zwb124** [comment]
3.1.5 yes, 3.2.1 no response in any case

**Comment by osy** [comment]
Oh! This isn't a UTM issue at all. I just updated to macOS 12.3.1 and I get the same issue (USB drives not detected, some other USB devices work fine). This seems to be a macOS bug...

Can you confirm by running 3.1.5 on 12.3.1?

**Comment by zwb124** [comment]
yes，3.1.5 is ok

[https://github.com/zwb124/tempfile/blob/main/202205071439.mp4?raw=true](url)

**Comment by osy** [comment]
Okay, I just unplugged and re-plugged in the drive and it still works so never mind the macOS bug theory...

**Comment by osy** [comment]
Can you confirm two things?

1. The drive is USB 3.0
2. You downloaded UTM 3.2.1 from GitHub release page OR TestFlight?

**Comment by zwb124** [comment]
1、USB 3.0 and 2.0 have this problem
2、utm 3.1.5 and 3.2.1 downloaded from GitHub release page

**Comment by osy** [comment]
Do you have a USB 2.0 only hub you can test by plugging your USB 3.0 device into?

**Comment by zwb124** [comment]
USB 2.0 USB flash disk and 3.0 portable hard disk have this problem in utm 3.2.1，utm 3.1.5 both ok

**Comment by osy** [comment]
[testlibusb.zip](https://github.com/utmapp/UTM/files/8644646/testlibusb.zip)

Can you download this and run:

```
$ xattr -d com.apple.quarantine testlibusb
$ ./testlibusb
$ sudo ./testlibusb
```

And post the output?

**Comment by zwb124** [comment]
[3:21] ~/Downloads % ./testlibusb
Dev (bus 2, device 1): 0951 - 1643 speed: 480M
  Manufacturer:              Kingston
  Product:                   DataTraveler G3
[3:21] ~/Downloads % sudo ./testlibusb
Dev (bus 2, device 1): 0951 - 1643 speed: 480M
  Manufacturer:              Kingston
  Product:                   DataTraveler G3
[3:21] ~/Downloads %


2022年5月7日 15:18，osy ***@***.******@***.***>> 写道：



testlibusb.zip<https://github.com/utmapp/UTM/files/8644646/testlibusb.zip>

Can you download this and run:

$ xattr -d com.apple.quarantine testlibusb
$ ./testlibusb
$ sudo ./testlibusb


And post the output?

**Comment by osy** [comment]
Can you run `sudo /Applications/UTM.app/Contents/MacOS/UTM`, create a new empty VM, start it and try to attach USB (you do not need to install any OS).

**Comment by zwb124** [comment]
I've tried this before, and the result is the same.

2022年5月7日 15:31，osy ***@***.******@***.***>> 写道：



Can you run sudo /Applications/UTM.app/Contents/MacOS/UTM, create a new empty VM, start it and try to attach USB (you do not need to install any OS).

**Comment by osy** [comment]
Do you have another Mac you can test with?

Any chance you can test 3.2.0? (You’ll need to workaround the vmport=off bug)

**Comment by zwb124** [comment]
3.2.0 Starting a VM shows an empty "Error" dialog.create a new empty vm is the same，so I can't test

I only have one MAC

**Comment by osy** [comment]
Yes that’s what I meant by the vmport=off bug. Please read the end of https://github.com/utmapp/UTM/releases/tag/v3.2.0 for the workaround.

**Comment by zwb124** [comment]
Thank you very much for your patience. It seems that this problem can not be solved in a short time. I don't need to upgrade to the latest version of UTM very urgently, so I don't want to toss around. Let's do it for the time being. Thank you

**Comment by osy** [comment]
Okay, as I am unable to reproduce this bug, I will have to move it to the future. If other people are experiencing this issue (including other people in this thread), please reply with the following:

1. What is the USB device that is having issues?
2. What version of UTM and macOS (including if it's Apple Silicon or Intel)?
3. What version of UTM did the same device last work on?
4. Do you see your device listed when you click the USB icon? If so, do you get an error message when you select it?
5. Follow https://github.com/utmapp/UTM/issues/3975#issuecomment-1120153876 and post the results.

**Comment by peterboivin** [comment]
What is the USB device that is having issues?
Midi Controller that has USB as connector.
What version of UTM and macOS (including if it's Apple Silicon or Intel)?
v.3.2.3 and earlier versions as well
Mac host is Mac Silicon
Guest is Mac from UTM's download
What version of UTM did the same device last work on?
It has never worked.  I started using UTM at v.3.15
Do you see your device listed when you click the USB icon? If so, do you get an error message when you select it?
No I don't see it.
Follow https://github.com/utmapp/UTM/issues/3975#issuecomment-1120153876 and post the results.

peter@MacStudios-Music-Virtual-Machine Downloads % ./testlibusb 
Dev (bus 13, device 2): 05AC - 8105 speed: 12M
  Manufacturer:              Apple Inc.
  Product:                   Virtual USB Keyboard
Dev (bus 13, device 1): 05AC - 8106 speed: 12M
  Manufacturer:              Apple Inc.
  Product:                   Virtual USB Digitizer
peter@MacStudios-Music-Virtual-Machine Downloads % 

One question I have is there any spice guest tool I need to install?  I have been looking for one, but don't see any.

**Comment by osy** [comment]
@peterboivin If you don't see it when clicking the USB button on the toolbar, then nothing you install in the guest VM can change that. To be clear, do you see your midi controller running `testlibusb`? Is it "Virtual USB Digitizer"?

**Comment by peterboivin** [comment]
The USB button on the toolbar has always been greyed out.  No I don't see the Midi Controller.  When the Midi Controller is turned on or off, Virtual USB Digitizer remains.

So I guess the problem is how to fix the USB button.

**Comment by osy** [comment]
If it’s grayed out this isn’t an issue and isn’t related to what’s described here. You’re either not running QEMU or you’re using console mode. Both of which don’t support USB.

**Comment by peterboivin** [comment]
I am new to UTM.  Do I need to run QEMU as well as UTM?  And I don't know what console mode is, I am UTM as the GUI instance.

**Comment by osy** [comment]
If you’re running macos it’s not QEMU. Anything else is QEMU. If you can see graphical interface in your VM it’s not console mode.

**Comment by peterboivin** [comment]
Well my question is am I not doing something to make "capture mouse cursor", "USB devices", "Drive Image options" and "Shared folder" to be greyed out in the toolbar?

**Comment by osy** [comment]
You’re probably trying to run macos which doesn’t use QEMU.

**Comment by peterboivin** [comment]
So using Mac OS as a guest I won't have the ability to use USB? My thinking is if I see USB greyed out, then I can't use it. If it is enabled in the toolbar, then I can use it.

**Comment by osy** [comment]
There is no support for USB for macOS guests. It is using a different backend than everything else (QEMU). This issue is about not recognizing a connected USB device, not about the USB option not being available.

**Comment by peterboivin** [comment]
Thanks for your response.  I don't really care if the option is available or not. I just wanted to be able to use USB.  Now that I know that I can't, I'll try another solution.  Again thank. you.

**Comment by haima23** [comment]
Okay, as I am unable to reproduce this bug, I will have to move it to the future. If other people are experiencing this issue (including other people in this thread), please reply with the following:

What is the USB device that is having issues? An stick with Bar Ilan Responsa software
What version of UTM and macOS (including if it's Apple Silicon or Intel)? UTM 3.2.3 and  M1 Pro with 13.4
What version of UTM did the same device last work on? I don't remember  but it was work.
Do you see your device listed when you click the USB icon? If so, do you get an error message when you select it? I don't see.

**Comment by osy** [comment]
@haima23 please do item 5

**Comment by osy** [comment]
That’s fine item 5 does not require UTM but to download the attached program.

**Comment by chrisx8** [comment]
I'm having this issue with the latest version of UTM (v3.2.3) on MacOS 12.4 (Apple Silicon). UTM just doesn't recognize any USB device, even in the USB device menu in the top-right of VM windows.

1. What is the USB device that is having issues?
   Seemingly all of them, including a SanDisk USB 3.0 flash drive, a generic JMicron based USB3.0-SATA enclosure, and a Yubikey 5 (USB 2.0).
2. What version of UTM and macOS (including if it's Apple Silicon or Intel)?
   UTM v3.2.3, MacOS 12.4, Apple Silicon
3. What version of UTM did the same device last work on?
   v3.1.5
4. Do you see your device listed when you click the USB icon? If so, do you get an error message when you select it?
   No device listed.
5. Follow https://github.com/utmapp/UTM/issues/3975#issuecomment-1120153876 and post the results.
   I was moving USB devices around because I don't have enough ports...
  ```
  $ ./testlibusb
  Dev (bus 2, device 1): 1050 - 0407 speed: 12M
    Manufacturer:              Yubico
    Product:                   YubiKey OTP+FIDO+CCID
  Dev (bus 0, device 1): 152D - 0578 speed: 5G
    Manufacturer:              JMicron
    Product:                   USB to ATA/ATAPI Bridge
  
  $ sudo ./testlibusb
  Dev (bus 2, device 1): 1050 - 0407 speed: 12M
    Manufacturer:              Yubico
    Product:                   YubiKey OTP+FIDO+CCID
  Dev (bus 0, device 1): 152D - 0578 speed: 5G
    Manufacturer:              JMicron
    Product:                   USB to ATA/ATAPI Bridge
  
  $ ./testlibusb
  Dev (bus 2, device 1): 0781 - 5591 speed: 5G
    Manufacturer:              SanDisk
    Product:                   Ultra USB 3.0
  Dev (bus 0, device 1): 152D - 0578 speed: 5G
    Manufacturer:              JMicron
    Product:                   USB to ATA/ATAPI Bridge
  
  $ sudo ./testlibusb
  Dev (bus 2, device 1): 0781 - 5591 speed: 5G
    Manufacturer:              SanDisk
    Product:                   Ultra USB 3.0
  Dev (bus 0, device 1): 152D - 0578 speed: 5G
    Manufacturer:              JMicron
    Product:                   USB to ATA/ATAPI Bridge
  ```

**Comment by osy** [comment]
@chrisx8 are the two devices that gets listed in testlibusb what you expect? Are you plugging them directly into your computer or through a usb hub (or a hub in your display)?

**Comment by chrisx8** [comment]
@osy testlibusb listed everything I plugged in. Everything is plugged in directly to the laptop (MacBook Pro 14", M1 Pro).

**Comment by osy** [comment]
Can you do this after clicking the USB button on the toolbar and not seeing any devices:

1. Open Activity Monitor
2. Find UTM process and double click
3. Click "Sample", copy paste the text to a .txt file, and attach it here.

**Comment by chrisx8** [comment]
@osy I did this for both v3.1.5 (works as expected) and v3.2.3 (no USB detected). See Sample output below:

[sample_3.1.5.txt](https://github.com/utmapp/UTM/files/8717738/sample_3.1.5.txt)
[sample_3.2.3.txt](https://github.com/utmapp/UTM/files/8717739/sample_3.2.3.txt)

**Comment by osy** [comment]
It was quite a journey but I finally managed to find the root cause: https://gitlab.freedesktop.org/spice/spice-gtk/-/issues/157

**Comment by osy** [comment]
And this is why you shouldn't update all your dependencies at once. I had to sift through QEMU, libusbredir, libusb, spice-gtk and finally find the root cause which is a bad logic (introduced 2 years ago!!) that always ignores USB devices with address 0x1. Now the question is how come nobody else who uses SPICE ran into this before? Is there something on Linux that precludes devices from having address 0x1?

**Comment by zwb124** [comment]
The USB problem has been solved. Thank you very much！

**Comment by soumik00** [comment]
Hiii 👋🏿
I am facing problems to connect usb adapter on UTM(Mac m1)..... plz anyone help me😇
<img width="912" alt="Screenshot 2022-09-06 at 7 13 56 PM" src="https://user-images.githubusercontent.com/78477427/188651084-18f61f63-905d-4000-9ef8-7ffc09ca5dc1.png">
<img width="820" alt="Screenshot 2022-09-06 at 7 14 07 PM" src="https://user-images.githubusercontent.com/78477427/188651155-122d0d90-4690-4c34-bdb8-5669800a854a.png">

**Comment by binnichtaktiv** [comment]
> Okay, as I am unable to reproduce this bug, I will have to move it to the future. If other people are experiencing this issue (including other people in this thread), please reply with the following:
> 
> 1. What is the USB device that is having issues?
> 2. What version of UTM and macOS (including if it's Apple Silicon or Intel)?
> 3. What version of UTM did the same device last work on?
> 4. Do you see your device listed when you click the USB icon? If so, do you get an error message when you select it?
> 5. Follow [USB device not recognized #3975 (comment)](https://github.com/utmapp/UTM/issues/3975#issuecomment-1120153876) and post the results.

What is the USB device that is having issues? **### _SanDisk 3.2Gen1 or any other usb stick i try_**
What version of UTM and macOS (including if it's Apple Silicon or Intel)? ### **### _UTM 4.0.9 macOS Ventura 13.0 m1 iMa_**c
What version of UTM did the same device last work on? ### **_thats my first time using UTM_**
Do you see your device listed when you click the USB icon? If so, do you get an error message when you select it? ### **_When i select usb 3.0 in vm settings there is nothing just the utm pop up to allow the stick to connect to the vm nothing more. not in device manager etc. when i select usb 2.0 i get a error message in my vm (win11) that there is a problem with this device(there is no problem its working fine on macos and on my laptop(win10))_**
Follow https://github.com/utmapp/UTM/issues/3975#issuecomment-1120153876 and post the results. 

Last login: Thu Oct 27 18:10:05 on ttys000
jonasb.@iMacvonJonas ~ % cd /Users/jonasb./Downloads 
jonasb.@iMacvonJonas Downloads % xattr -d com.apple.quarantine testlibusb
jonasb.@iMacvonJonas Downloads % ./testlibusb
Dev (bus 1, device 4): 0781 - 5583 speed: 5G
  Manufacturer:               USB
  Product:                    SanDisk 3.2Gen1
Dev (bus 1, device 6): 05E3 - 0749 speed: 5G
  Manufacturer:              Generic
  Product:                   USB3.0 Card Reader
Dev (bus 1, device 2): 2109 - 2817 speed: 480M
  Manufacturer:              VIA Labs, Inc.         
  Product:                   USB2.0 Hub             
Dev (bus 1, device 1): 2109 - 0817 speed: 5G
  Manufacturer:              VIA Labs, Inc.         
  Product:                   USB3.0 Hub             
jonasb.@iMacvonJonas Downloads % sudo ./testlibusb
Password:
Dev (bus 1, device 4): 0781 - 5583 speed: 5G
  Manufacturer:               USB
  Product:                    SanDisk 3.2Gen1
Dev (bus 1, device 6): 05E3 - 0749 speed: 5G
  Manufacturer:              Generic
  Product:                   USB3.0 Card Reader
Dev (bus 1, device 2): 2109 - 2817 speed: 480M
  Manufacturer:              VIA Labs, Inc.         
  Product:                   USB2.0 Hub             
Dev (bus 1, device 1): 2109 - 0817 speed: 5G
  Manufacturer:              VIA Labs, Inc.         
  Product:                   USB3.0 Hub             
jonasb.@iMacvonJonas Downloads %

**Comment by c-goes** [comment]
I can't connect a NVMe disk that is in an USB enclosure to a Linux VM. This is the log from the kernel.
<img width="620" alt="Bildschirm­foto 2022-11-12 um 22 35 57" src="https://user-images.githubusercontent.com/23212798/201495481-f287925c-6cd5-43e3-94ea-e7abfc3049f1.png">

**Comment by lukechable** [comment]
I also can't get any USB external drives to show. But more confusingly, i NEVER have the input menu available that is showing for everyone else on the left sidebar. I've updated to the latest beta in an attempt to get it working, but still not INPUT option in the menu... Not sure what i'm doing wrong here.
I'm on an M1 Max Macbook, Trying to do latest ventura virtualized. Any tips to get that input option showing would be amazing...

I've taken an image from above, showing the highlighted input option in the sidebar menu. This is what i don't have, no matter what i do.

![228114810-7dca9389-24d2-4119-9f4f-0e17cb0723b9](https://user-images.githubusercontent.com/7068039/228115031-ec76cc36-757b-4248-b6c4-56b2190060fa.png)

**Comment by zwb124** [comment]
You can try adjusting each setting in the input options one by one, then start the virtual machine, and after that, close the virtual machine. Then set the input options back to their original settings and start the virtual machine again to see if the issue is fixed. If not, you can continue modifying the settings and repeat the above steps until the issue is resolved.

**Comment by lukechable** [comment]
> 
<img width="809" alt="Screenshot 2023-03-28 at 4 42 24 pm" src="https://user-images.githubusercontent.com/7068039/228139417-f95c5d24-b3b2-4596-a26d-3b5037439942.png">

I don't have any input options at all.

**Comment by djmtype** [comment]
Having the same issues as @binnichtaktiv. My devices are shown correctly in USB list. But, as soon as I select one, I get a popup in Windows, stating it's unrecognized. Samsung Evo - ExFat format. Using UTM 4.1.6, Windows 11 arm on MacOS 13.3.1, M1 arm

**Comment by huuub** [comment]
Why is this issue closed? It is clearly still an issue?

**Comment by Corentin7301** [comment]
Hi there!
Has a solution finally been found, as I have the same problem of USB devices not being recognized or even detected...
I'm on `UTM : 4.3.5` and whether it's with a Parrot VM or Windows 7 VM, it doesn't work.
I'm using a Macbook Pro M1.
I have the two confirmation windows that open when the USB device is connected.

**Comment by dharmtej-0206** [comment]
Does flashing software or firmware on your phone work in UTM? They do open and work fine, but those applications are not able to detect my Android phone. Is there a workaround? By the way, I have used the Mi Flash Tool, but sadly, it has no Mac alternatives. My device is m2 running sonoma 14.1. Any suggestions is accepted let me know if there isa workaround for this issue

**Comment by NaotoFujihiro** [comment]
I faced the same issue.
In my case, allowing UTM to access the USB device was needed.

Here's my environment.

`MacBook M1
$ sw_vers
ProductName:		macOS
ProductVersion:		14.1
BuildVersion:		23B74
`

`UTM
Version 4.4.5 (94)
`

![Screenshot 2023-12-25 at 14 56 15](https://github.com/utmapp/UTM/assets/40661724/82b85f08-0e5b-4d66-a4a9-675edd02a52d)
![Screenshot 2023-12-25 at 14 56 53](https://github.com/utmapp/UTM/assets/40661724/7b5a1f97-5c47-48ec-bab7-3dc1061d92c2)
![Screenshot 2023-12-25 at 14 57 00](https://github.com/utmapp/UTM/assets/40661724/a2e9c796-9a42-4b0a-b577-e77dff1c96b1)

**Comment by Yuriy-Nayda** [comment]
> I faced the same issue. In my case, allowing UTM to access the USB device was needed.
> 
> Here's my environment.
> 
> ```
> $ sw_vers
> ProductName:		macOS
> ProductVersion:		14.1
> BuildVersion:		23B74
> ```
> 
> ```
> Version 4.4.5 (94)
> ```
> 
> ![Screenshot 2023-12-25 at 14 56 15](https://private-user-images.githubusercontent.com/40661724/292716023-82b85f08-0e5b-4d66-a4a9-675edd02a52d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MzA5ODAsIm5iZiI6MTcxMTUzMDY4MCwicGF0aCI6Ii80MDY2MTcyNC8yOTI3MTYwMjMtODJiODVmMDgtMGU1Yi00ZDY2LWE0YTktNjc1ZWRkMDJhNTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA5MTEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5MjNmNWM5Y2JmYzE5Nzc5OGFkMjg4Y2Y1M2YyZDZiMjIyNjhlMDA0MWVmMmFkYmNhZDI1NzU4ZmY3YjZiZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KQsWfOljFtPIJpeDanBnG_-7ymGcd188mAx6VY0pknk) ![Screenshot 2023-12-25 at 14 56 53](https://private-user-images.githubusercontent.com/40661724/292716028-7b5a1f97-5c47-48ec-bab7-3dc1061d92c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MzA5ODAsIm5iZiI6MTcxMTUzMDY4MCwicGF0aCI6Ii80MDY2MTcyNC8yOTI3MTYwMjgtN2I1YTFmOTctNWM0Ny00OGVjLWJhYjctM2RjMTA2MWQ5MmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA5MTEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyODlkMjNmZDU4NWQzZmI5NjNhNDljYmU3OWNjYTZmYzgzMmU5N2QxM2EyN2YwMjUxMWY0NGI1Nzc5ZGVmMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SPVSOmBlPVH5Lv2PMqBU3Gl3115ZPQUEpWciV4ZjP0Y) ![Screenshot 2023-12-25 at 14 57 00](https://private-user-images.githubusercontent.com/40661724/292716033-a2e9c796-9a42-4b0a-b577-e77dff1c96b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MzA5ODAsIm5iZiI6MTcxMTUzMDY4MCwicGF0aCI6Ii80MDY2MTcyNC8yOTI3MTYwMzMtYTJlOWM3OTYtOWE0Mi00YjBhLWI1NzctZTc3ZGZmMWM5NmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA5MTEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMDg0NWVkZDIyNzg3ODg3OWNiNmIyYTg2MTM1YWZlZWRlODMxNWNmYzZjNzZhY2Y2MzI4ZmUyMDI5YWU3YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4sCJwPr7RwPEqC1LDGjh2MFVeRtKaJITslCCKa9IRC0)

Have same issue. 500GB SSD is well seen on VMWare Fusion , from where i did a backup of Windows 10 to this SSD, and then when conecting same SSD to UTM, windows on UTM can not see it saying device is not recognized.  As well MacOS when SSD connected to it sees it well.

**Comment by Yuriy-Nayda** [comment]
that's crazy: i have used another type-c to type-c cable and mentioned above by me SSD got connected to the Windows on UTM!!

**Comment by safts** [comment]
> that's crazy: i have used another type-c to type-c cable and mentioned above by me SSD got connected to the Windows on UTM!!

Funny enough, same thing happened to me. I was using the manufacturer's cable, which is a beefy USB3 type c cable. Switching to a USB2 one made my drive available in the linux VM (I can see it with `fdisk -l` where previously I could not). Crazy!

**Comment by kristof-dragon** [comment]
I can second this, USB3 devices in general fail to pass through despite enabling all the options mentioned in the messages.

**Comment by elendirx** [comment]
I have the same issue with new 500GB usb pen drive. Tried all combinations in the USB settings. This issue should be re-opened.

**Comment by steve500** [comment]
+1 same issues using an "ssk" brand USB 3.0 nvme drive enclosure. Will not pass through with same errors in Windows noted above.

**Comment by BeerRabbi** [comment]
Same issue as steve500. SSK 1TB USB3/USBC.

**Comment by navigator085** [comment]
UTM doesn't support USB 3.2 Gen 2 and Gen 3 (per [[ideologysec](https://github.com/ideologysec))](https://github.com/utmapp/UTM/issues/4167#issuecomment-1168016437). The post is from 2022 but apparently in 2025 it's still current.

This explains the weird behaviors recounted here. If you connect your Gen2 device with a USB 3.0 cable, the device will connect to the computer via USB 3.0 (same for a 2.0 cable, a 3.2 Gen 1 one, etc), thus becoming visible to UTM.

So yes, the solution is to use a cable (or even a USB hub) from an older, supported, generation. 
An USB 3.0 cable is preferable to changing the VM config to USB 2.0, even if that works, because the loss in performance is lesser.

An alternative solution would be for UTM (QEMU?) to actually support USB 3.2.
