### ISSUE TITLE
cannot open ANY 32bit applications on a Maverick system (guest) embedded on a Vetura OS (host) installed on MacBook Air with M2 chips.

### ISSUE THREAD

**Issue by pedroponchojr** [utmapp/UTM#4990]
Hey guys, I'm in trouble, in a serious quandary. Please help me out. THIS MIGHT BE THE FIRST REPORT OF THIS KIND. ANY IDEA OR ANY SUGGESTION IS WELCOME. Thanks!

Symptom: cannot open ANY 32bit applications on a Maverick system (guest) embedded on a Vetura OS (host) installed on MacBook Air with M2 chips.

Details:
UTM version 4.1.5
Maverick OS X 10.9.5 (guest)
Ventura 13.2 (22D49) (host)
MacBook Air (M2, 2022)
*I have used "OS X 10.9 (config only).utm" from
https://github.com/adespoton/utmconfigs

List of the pieces of software that have just collapsed:
Bento
eReader
Mariner Calc
Oxford Learner's Thesaurus
File Buddy 10
Tex-Edit Plus
DVD Player (that has come with Maverick)

Crash reports from an application:

Process:         DVD Player [378]
Path:            /Applications/DVD Player.app/Contents/MacOS/DVD Player
Identifier:      com.apple.DVDPlayer
Version:         5.7 (5500.48.2)
Build Info:      DVDPlayer-5500048002000000~1
Code Type:       X86 (Native)
Parent Process:  launchd [236]
Responsible:     DVD Player [378]
User ID:         501

Date/Time:       2023-02-03 15:57:05.157 -0800
OS Version:      Mac OS X 10.9.5 (13F34)
Report Version:  11
Anonymous UUID:  C9C5D3DF-6C70-A4E2-BCD4-F56194248C17

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x000000000068a000

VM Regions Near 0x68a000:
    VM_ALLOCATE            000000000067e000-000000000068a000 [   48K] rw-/rwx SM=PRV  
--> VM_ALLOCATE            000000000068a000-000000000068b000 [    4K] rw-/rwx SM=ALI  
    VM_ALLOCATE            000000000076f000-0000000000770000 [    4K] r--/rw- SM=ALI  

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.apple.CoreGraphics        	0x96f50359 CG::Chunk::apply_transform(CGAffineTransform const&) + 241
1   com.apple.CoreGraphics        	0x96f50259 CG::Path::Subpath::apply_transform(CGAffineTransform const&) + 37
2   com.apple.CoreGraphics        	0x96f50223 CG::Path::Sequence::apply_transform(CGAffineTransform const&) + 35
3   com.apple.CoreGraphics        	0x96f3e15c CG::Path::apply_transform(CGAffineTransform const&) + 64
4   com.apple.CoreGraphics        	0x96f500c5 CGPathCreateMutableCopyByTransformingPath + 163
5   com.apple.CoreGraphics        	0x96f4f384 CGFontCreateGlyphPath + 120
6   com.apple.CoreGraphics        	0x96f4f2af CGFontCreateGlyphBitmap + 355
7   com.apple.CoreGraphics        	0x96f4f09c CGGlyphBuilder::create_missing_bitmaps(CGGlyphIdentifier const*, unsigned long, CGGlyphBitmap const**) + 144
8   com.apple.CoreGraphics        	0x96f4eceb CGGlyphBuilder::lock_glyph_bitmaps(CGGlyphIdentifier const*, unsigned long, CGGlyphBitmap const**) + 149
9   libRIP.A.dylib                	0x996048b2 render_glyphs + 179
10  libRIP.A.dylib                	0x99603a4b draw_glyph_bitmaps + 1426
11  libRIP.A.dylib                	0x99602fda ripc_DrawGlyphs + 2041
12  com.apple.CoreGraphics        	0x9700c47e draw_glyphs + 1298
13  com.apple.CoreGraphics        	0x96f4e2e1 CGContextShowGlyphsWithAdvances + 493
14  com.apple.CoreText            	0x95400361 CTFontDrawGlyphsWithAdvances + 2979
15  com.apple.CoreText            	0x953ff700 TRun::DrawGlyphs(CGContext*, CFRange) const + 282
16  com.apple.CoreText            	0x953ff064 TLine::DrawGlyphs(CGContext*) const + 222
17  com.apple.CoreText            	0x953fef84 CTLineDraw + 40
18  com.apple.HIToolbox           	0x9bb3efb8 TCoreTextEngine::DrawThemeTextBox(THIThemeTextInfo*, CGRect const&, unsigned long, CGContext*) + 2130
19  com.apple.HIToolbox           	0x9baa6e2e DataEngine::DrawTextBox(void const*, CGRect const*, HIThemeTextInfo*, CGContext*) + 1906
20  com.apple.HIToolbox           	0x9baa66a5 HIThemeDrawTextBox + 335
21  com.apple.HIToolbox           	0x9baa6428 HIMenuBarView::DrawTextTitle(MenuData*, CGRect const*, __CFString const*, unsigned short, CGContext*, bool, bool) + 412
22  com.apple.HIToolbox           	0x9baa315e HIMenuBarView::DrawOnce(CGRect, CGRect, bool, bool, bool, bool, CGContext*) + 1620
23  com.apple.HIToolbox           	0x9baa2ac8 HIMenuBarView::DrawSelf(short, __HIShape const*, CGContext*) + 920
24  com.apple.HIToolbox           	0x9baa2561 HIView::DrawCacheOrSelf(short, __HIShape const*, CGContext*) + 361
25  com.apple.HIToolbox           	0x9baa23ec HIView::SendDraw(short, OpaqueGrafPtr*, __HIShape const*, CGContext*) + 518
26  com.apple.HIToolbox           	0x9bb64e7e HIView::RecursiveDrawComposited(__HIShape const*, __HIShape const*, unsigned long, HIView*, CGContext*, unsigned char, float) + 784
27  com.apple.HIToolbox           	0x9bb6511a HIView::RecursiveDrawComposited(__HIShape const*, __HIShape const*, unsigned long, HIView*, CGContext*, unsigned char, float) + 1452
28  com.apple.HIToolbox           	0x9bb64364 HIView::DrawComposited(short, OpaqueGrafPtr*, __HIShape const*, unsigned long, HIView*, CGContext*) + 890
29  com.apple.HIToolbox           	0x9bb63f9e HIView::Draw(short, OpaqueGrafPtr*, unsigned long) + 84
30  com.apple.HIToolbox           	0x9bb63f43 HIView::Render(unsigned long, CGContext*) + 45
31  com.apple.HIToolbox           	0x9baa0ca8 WindowData::PrepareForVisibility() + 176
32  com.apple.HIToolbox           	0x9ba9fa95 _ShowHideWindows + 355
33  com.apple.HIToolbox           	0x9ba9f92d ShowHide + 44
34  com.apple.HIToolbox           	0x9ba91134 MBWindows::CreateWindow(CGRect, unsigned int) + 546
35  com.apple.HIToolbox           	0x9ba90c5c MBWindows::GetWindowIDOnDisplay(unsigned int, unsigned char) + 172
36  com.apple.HIToolbox           	0x9ba90bab ___ZN15MenuBarInstance15ForEachWindowDoEU13block_pointerFvjjE_block_invoke + 60
37  com.apple.HIToolbox           	0x9ba90a17 MenuBarInstance::ForEachWindowDo(void (unsigned int, unsigned int) block_pointer) + 225
38  com.apple.HIToolbox           	0x9ba90720 MenuBarInstance::UpdateWindowBoundsAndResolution() + 150
39  com.apple.HIToolbox           	0x9ba90268 MenuBarInstance::Show(MenuBarAnimationStyle, unsigned char, unsigned char, unsigned char) + 382
40  com.apple.HIToolbox           	0x9babb7b3 SetMenuBarObscured + 313
41  com.apple.HIToolbox           	0x9baaa429 _DrawMenuBarOnDisplay + 82
42  com.apple.HIToolbox           	0x9bc82b49 DrawMenuBar + 19
43  com.apple.HIToolbox           	0x9bc53957 SetMenuBarFromNib + 324
44  com.apple.DVDPlayer           	0x0017822d 0xda000 + 647725
45  com.apple.DVDPlayer           	0x00144532 0xda000 + 435506
46  com.apple.DVDPlayer           	0x001441a2 0xda000 + 434594
47  com.apple.DVDPlayer           	0x000f3203 0xda000 + 102915
48  com.apple.DVDPlayer           	0x000f31b7 0xda000 + 102839
49  libdyld.dylib                 	0x93bbb701 start + 1

Thread 1:: Dispatch queue: com.apple.libdispatch-manager
0   libsystem_kernel.dylib        	0x900a4992 kevent64 + 10
1   libdispatch.dylib             	0x99257899 _dispatch_mgr_invoke + 238
2   libdispatch.dylib             	0x99257532 _dispatch_mgr_thread + 52

Thread 2:
0   libsystem_kernel.dylib        	0x900a4046 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x9b097dcf _pthread_wqthread + 372
2   libsystem_pthread.dylib       	0x9b09bcce start_wqthread + 30

Thread 3:
0   libsystem_kernel.dylib        	0x900a4046 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x9b097dcf _pthread_wqthread + 372
2   libsystem_pthread.dylib       	0x9b09bcce start_wqthread + 30

Thread 4:
0   libsystem_kernel.dylib        	0x900a4046 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x9b097dcf _pthread_wqthread + 372
2   libsystem_pthread.dylib       	0x9b09bcce start_wqthread + 30

Thread 0 crashed with X86 Thread State (32-bit):
  eax: 0x96f50272  ebx: 0xbff24ce0  ecx: 0x00689f78  edx: 0xbff24ce0
  edi: 0x96f502fb  esi: 0x0000000d  ebp: 0xbff24bc8  esp: 0xbff24bc0
   ss: 0x00000023  efl: 0x00000202  eip: 0x96f50359   cs: 0x0000001b
   ds: 0x00000023   es: 0x00000023   fs: 0x00000000   gs: 0x0000000f
  cr2: 0x0068a000
  
Logical CPU:     2
Error Code:      0x00000004
Trap Number:     14

Binary Images:
   0xda000 -   0x2cafff  com.apple.DVDPlayer (5.7 - 5500.48.2) <CB5B6350-4EED-34C6-8CA9-4526AA587C50> /Applications/DVD Player.app/Contents/MacOS/DVD Player
  0x35e000 -   0x38bff2  com.apple.MediaUI (1.1 - 27) <A1D9759E-101F-33C4-BD77-BF886CBAB2B7> /System/Library/PrivateFrameworks/MediaUI.framework/Versions/A/MediaUI
  0x3b2000 -   0x51bff8  com.apple.dvdplayback (5.8.0 - 5800.4.9) <6348E9AC-ECE8-35E7-8F03-8D49990DD112> /System/Library/Frameworks/DVDPlayback.framework/Versions/A/DVDPlayback
0x8fe55000 - 0x8fe87417  dyld (239.4) <0F2176BD-4239-3506-BA41-3B885269520E> /usr/lib/dyld
0x90008000 - 0x90036ff3  com.apple.DebugSymbols (106 - 106) <FC70F4C9-B2A6-352F-9563-6C085E9DDDB8> /System/Library/PrivateFrameworks/DebugSymbols.framework/Versions/A/DebugSymbols
0x90037000 - 0x90053fff  libCRFSuite.dylib (34) <FFF76EBA-DF35-3A5F-857F-3F4B1C9F4C77> /usr/lib/libCRFSuite.dylib
0x90054000 - 0x90058fff  com.apple.CommonPanels (1.2.6 - 96) <E7CA63C6-CEE9-3F0A-93A7-C12C653FFB80> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/CommonPanels.framework/Versions/A/CommonPanels
0x90064000 - 0x9008bfff  com.apple.CoreVideo (1.8 - 117.2) <A53FDD90-F200-3F7C-8A8E-5DE36D3DFBB0> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
0x9008c000 - 0x900a9ff4  libsystem_kernel.dylib (2422.115.4) <011434BC-0EFD-35E9-B76D-A22B76DC83DC> /usr/lib/system/libsystem_kernel.dylib
0x900aa000 - 0x903bdfef  com.apple.CoreAUC (6.25.00 - 6.25.00) <84677812-2943-328C-B4E0-5E37A6181195> /System/Library/PrivateFrameworks/CoreAUC.framework/Versions/A/CoreAUC
0x903be000 - 0x90414ff6  com.apple.ScalableUserInterface (1.0 - 1) <2C81641B-FA30-32FF-8B3E-3CB9BF53B2D9> /System/Library/Frameworks/QuartzCore.framework/Versions/A/Frameworks/ScalableUserInterface.framework/Versions/A/ScalableUserInterface
0x90415000 - 0x90451ff4  com.apple.RemoteViewServices (2.0 - 94) <BEEE6ADF-7DA3-3D68-BCB0-9863BE1A1F46> /System/Library/PrivateFrameworks/RemoteViewServices.framework/Versions/A/RemoteViewServices
0x90452000 - 0x90456ffa  libGIF.dylib (1044) <075D0A69-DEEC-3712-93F7-DC78FECCC0FF> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libGIF.dylib
0x90457000 - 0x904ccff1  com.apple.ApplicationServices.ATS (360 - 363.3) <FD423680-01A1-357A-89A7-33910A87DE65> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/ATS
0x904cd000 - 0x904d6fff  com.apple.speech.recognition.framework (4.2.4 - 4.2.4) <CF8E5706-F744-3139-8A51-D52BF055D19F> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SpeechRecognition.framework/Versions/A/SpeechRecognition
0x904d7000 - 0x904daffa  libCGXType.A.dylib (599.35.4) <12865AFC-BF83-36AB-A42E-331D39C8FD68> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libCGXType.A.dylib
0x90512000 - 0x90521fff  libGL.dylib (9.6.1) <885E9C1F-11C7-347D-BE10-522A40A46596> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib
0x90765000 - 0x90789ff3  libc++abi.dylib (49.1) <43A04ACF-97A5-35ED-B454-6B5C0CF0F99D> /usr/lib/libc++abi.dylib
0x9078a000 - 0x9078bffd  libunc.dylib (28) <22A126A1-DCFB-3BE5-A66B-C973F0A5D839> /usr/lib/system/libunc.dylib
0x908b8000 - 0x908e9ffa  libsystem_m.dylib (3047.16) <28E614E8-7802-3E84-960A-AD4721EF10F7> /usr/lib/system/libsystem_m.dylib
0x908ea000 - 0x90920fff  com.apple.IconServices (25 - 25.17) <A4B5242B-765E-3D58-B066-BBEDB5947AAD> /System/Library/PrivateFrameworks/IconServices.framework/Versions/A/IconServices
0x90921000 - 0x90933fff  libsystem_asl.dylib (217.1.4) <51EB17C9-9F5B-39F3-B6CD-8EF238B05B89> /usr/lib/system/libsystem_asl.dylib
0x90934000 - 0x9093dfff  com.apple.audio.SoundManager (4.1 - 4.1) <68B7CEB7-AF09-3E24-8548-6ABF065B5186> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/CarbonSound.framework/Versions/A/CarbonSound
0x91345000 - 0x91439fff  libFontParser.dylib (111.1) <D8F9B2A4-41A6-3407-8D80-13A841F97BE5> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontParser.dylib
0x9143a000 - 0x9143afff  com.apple.Accelerate (1.9 - Accelerate 1.9) <C85070A7-D942-3CFA-981F-5864480788C8> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
0x9143b000 - 0x9143bfff  libkeymgr.dylib (28) <1B097DEA-011E-3B1C-86D5-6C7FAD5C765A> /usr/lib/system/libkeymgr.dylib
0x9143c000 - 0x91456ff7  com.apple.GenerationalStorage (2.0 - 160.3) <D39634C9-93BF-3C74-828B-4809EF895DA0> /System/Library/PrivateFrameworks/GenerationalStorage.framework/Versions/A/GenerationalStorage
0x91457000 - 0x916d0ff2  com.apple.security (7.0 - 55471.14.18) <7A58D9DE-D68B-37F7-87EF-4A3575DA09B7> /System/Library/Frameworks/Security.framework/Versions/A/Security
0x916d1000 - 0x916dcff6  com.apple.NetAuth (5.0 - 5.0) <3B2E9615-EE12-38FC-BDCF-09529FF9464B> /System/Library/PrivateFrameworks/NetAuth.framework/Versions/A/NetAuth
0x916dd000 - 0x916e2ff6  libcompiler_rt.dylib (35) <9924DF2E-D80B-3A21-920D-544A4597203F> /usr/lib/system/libcompiler_rt.dylib
0x917ab000 - 0x918bbfed  com.apple.MediaControlSender (2.0 - 200.34.4) <48A88743-4EB7-364B-968F-43C17FFCEB97> /System/Library/PrivateFrameworks/MediaControlSender.framework/Versions/A/MediaControlSender
0x918bc000 - 0x9191dff7  com.apple.Symbolication (1.4 - 129.0.2) <FB0121DF-F27B-39A3-92CA-B46981D322D5> /System/Library/PrivateFrameworks/Symbolication.framework/Versions/A/Symbolication
0x9191e000 - 0x9191efff  com.apple.ApplicationServices (48 - 48) <7967F6FA-2984-3CC3-AD9A-7B9AEC562A2A> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
0x9191f000 - 0x9192fff5  com.apple.LangAnalysis (1.7.0 - 1.7.0) <71DE7754-0A47-3F35-B1BF-B1FE7E1311E0> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/LangAnalysis.framework/Versions/A/LangAnalysis
0x91a0b000 - 0x92629ff3  com.apple.AppKit (6.9 - 1265.21) <1D31697B-6F33-3239-BACE-5D1361B1F79A> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
0x9262a000 - 0x92645ff5  com.apple.openscripting (1.4 - 157) <5C161A52-8D2F-3D56-A988-05727BED7A59> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/OpenScripting.framework/Versions/A/OpenScripting
0x92646000 - 0x92677ffb  com.apple.GSS (4.0 - 2.0) <145B389F-AC1E-3817-835D-8EA263E96EA5> /System/Library/Frameworks/GSS.framework/Versions/A/GSS
0x92678000 - 0x927affff  com.apple.desktopservices (1.8.3 - 1.8.3) <3574872B-435C-3AB8-A453-02A33A771CDB> /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv
0x927b0000 - 0x927b7ff7  com.apple.XPCService (2.0 - 1) <94783930-9E46-394F-B1B2-9CA57CBA2D25> /System/Library/PrivateFrameworks/XPCService.framework/Versions/A/XPCService
0x927b8000 - 0x927c2ff7  com.apple.speech.synthesis.framework (4.7.1 - 4.7.1) <C4CC55E5-6CC4-307E-9499-AF89A6463AF4> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis
0x927c3000 - 0x927dbff7  libsystem_malloc.dylib (23.10.1) <CB52555E-0F5B-31E3-A42A-FD4F930E2192> /usr/lib/system/libsystem_malloc.dylib
0x927dc000 - 0x9281efff  libGLU.dylib (9.6.1) <0655104D-2F22-36CE-955B-52A533CA70D5> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib
0x9281f000 - 0x92822ff3  com.apple.AppleSystemInfo (3.0 - 3.0) <4586B503-A0A8-3654-AA48-D2F9FA0188CB> /System/Library/PrivateFrameworks/AppleSystemInfo.framework/Versions/A/AppleSystemInfo
0x9282a000 - 0x92980ff0  libBLAS.dylib (1094.5) <74310C2F-4FDB-3995-A01A-5AFB83010A43> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
0x92981000 - 0x92998ff4  com.apple.CoreMediaAuthoring (2.2 - 947) <958EE809-D21F-3C88-8D87-B3A5E4C3FCA6> /System/Library/PrivateFrameworks/CoreMediaAuthoring.framework/Versions/A/CoreMediaAuthoring
0x929a4000 - 0x929afffb  libcommonCrypto.dylib (60049) <F8E60C43-22EE-3E0B-9546-3365056901F1> /usr/lib/system/libcommonCrypto.dylib
0x929b0000 - 0x929bcff7  com.apple.OpenDirectory (10.9 - 173.90.1) <D50773D6-A261-390E-B159-0C161EA7C457> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory
0x929bd000 - 0x929c6fff  com.apple.DiskArbitration (2.6 - 2.6) <92F7575A-AA20-34D9-BB26-2CC8C3CCAFEB> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
0x929d3000 - 0x92a64fff  com.apple.ColorSync (4.9.0 - 4.9.0) <8366AE10-0396-3100-B87A-A176E8ECE7B6> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ColorSync.framework/Versions/A/ColorSync
0x92a65000 - 0x92abafff  libc++.1.dylib (120) <10C0A136-64F9-3CC2-9420-013247032120> /usr/lib/libc++.1.dylib
0x92abb000 - 0x92c48ffb  com.apple.CFNetwork (673.3 - 673.3) <2C900A5F-9E29-3636-846D-68B24774E82A> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
0x931b7000 - 0x931d4ffb  libresolv.9.dylib (54) <3EC12A7F-6BA1-3976-9F1F-6A4B76303028> /usr/lib/libresolv.9.dylib
0x93202000 - 0x93202fff  com.apple.CoreServices (59 - 59) <06747539-5035-3307-8645-9BC4E7F89023> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
0x93203000 - 0x933ab4af  libobjc.A.dylib (551.1) <31CBE178-E972-30D1-ADC6-4B8345CAE326> /usr/lib/libobjc.A.dylib
0x93498000 - 0x93499fff  libSystem.B.dylib (1197.1.1) <6BDF4FCA-2E77-3F74-ADB2-54049B426E32> /usr/lib/libSystem.B.dylib
0x9349b000 - 0x934c3fff  libsystem_info.dylib (449.1.3) <BB68E8CC-422F-3121-8C86-D0F766FB696D> /usr/lib/system/libsystem_info.dylib
0x934c4000 - 0x934c5fff  libremovefile.dylib (33) <ED35EA79-EB06-3B84-A6D4-B1A9D6B8648D> /usr/lib/system/libremovefile.dylib
0x934c6000 - 0x934d3fff  com.apple.AppleFSCompression (56.92.1 - 1.0) <D2E7A2DF-9E5B-35E6-9CCD-0D40ADA7E021> /System/Library/PrivateFrameworks/AppleFSCompression.framework/Versions/A/AppleFSCompression
0x934d4000 - 0x934d4fff  com.apple.Cocoa (6.8 - 20) <407DC9E6-BBCE-3D34-9BBB-00C90584FFDF> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
0x93544000 - 0x935affff  com.apple.Heimdal (4.0 - 2.0) <D6465D74-9351-3FF3-9561-AC149AEDB86F> /System/Library/PrivateFrameworks/Heimdal.framework/Versions/A/Heimdal
0x93651000 - 0x9374ffff  libJP2.dylib (1044) <E8873182-8B75-34A5-A104-BED94B0C6BF6> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJP2.dylib
0x93750000 - 0x937e7ff7  com.apple.ink.framework (10.9 - 207) <EF00BCCB-B270-3F3D-9424-EF5F4BC23E25> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Ink.framework/Versions/A/Ink
0x937e8000 - 0x937f1fff  com.apple.AppleSRP (5.0 - 1) <6B946F4B-7DC4-3E82-BF2C-BE0930E3CF47> /System/Library/PrivateFrameworks/AppleSRP.framework/Versions/A/AppleSRP
0x937f2000 - 0x9380aff7  com.apple.CFOpenDirectory (10.9 - 173.90.1) <7F3A0094-3A24-302C-9B64-C32C65750EDE> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/Frameworks/CFOpenDirectory.framework/Versions/A/CFOpenDirectory
0x93b0d000 - 0x93b18fff  com.apple.CrashReporterSupport (10.9 - 539) <10FE9B2D-404F-32B8-B3CA-CBA3524B4CFF> /System/Library/PrivateFrameworks/CrashReporterSupport.framework/Versions/A/CrashReporterSupport
0x93b49000 - 0x93b65ff9  com.apple.Ubiquity (1.3 - 289) <1CEDC83D-7282-3B4D-8CF7-4FE045012391> /System/Library/PrivateFrameworks/Ubiquity.framework/Versions/A/Ubiquity
0x93b66000 - 0x93bb7ffb  com.apple.CoreMedia (1.0 - 1273.54) <086865CC-7B9A-3B96-A3CB-4B90DAD5DC91> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
0x93bb8000 - 0x93bbbff7  libdyld.dylib (239.4) <98B79E09-15EC-3ED8-86F1-1B0558060286> /usr/lib/system/libdyld.dylib
0x93bbc000 - 0x93bd7ff6  libPng.dylib (1044) <D90105D1-B8AD-3649-A798-DA567D1C5B3A> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib
0x93c36000 - 0x93c38fff  libsystem_configuration.dylib (596.15) <E49AAD29-35C2-3EE2-AF4D-59514C4B478F> /usr/lib/system/libsystem_configuration.dylib
0x93c39000 - 0x9406dff7  com.apple.vision.FaceCore (3.0.0 - 3.0.0) <5B12F3E9-84F6-3183-B85D-FD19EF800ADB> /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/FaceCore
0x940d5000 - 0x940ddfff  liblaunch.dylib (842.92.1) <C180016C-F2DB-3D8B-A72D-5185CE67DFA2> /usr/lib/system/liblaunch.dylib
0x940de000 - 0x940fdff9  com.apple.framework.Apple80211 (9.4 - 940.60) <8CCF54EE-F3CA-38B3-BD61-DDBF99E37FCB> /System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Apple80211
0x940fe000 - 0x94102ffe  libCoreVMClient.dylib (58.1) <0EB8FFD7-AFED-3A63-810E-29629831D43D> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreVMClient.dylib
0x94103000 - 0x94161ffd  com.apple.AE (665.5 - 665.5) <54F2F247-160C-3A22-A6E3-5D49655A67AB> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
0x94246000 - 0x9424eff7  libCGCMS.A.dylib (599.35.4) <63B0F606-94B1-3355-909A-01C6F26A91F7> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libCGCMS.A.dylib
0x94256000 - 0x94294ff7  com.apple.NavigationServices (3.8 - 215) <A093AAF0-248E-313E-BA82-01F69E269895> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/NavigationServices.framework/Versions/A/NavigationServices
0x943a6000 - 0x94492ff7  libxml2.2.dylib (26) <32040145-6FD6-3AD2-B98B-39F73BF9AC47> /usr/lib/libxml2.2.dylib
0x94749000 - 0x9474dffc  com.apple.IOSurface (91.1 - 91.1) <70637267-4D54-3EFF-A929-54FC0A8A907A> /System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface
0x9474e000 - 0x9478bff7  libauto.dylib (185.5) <CD008E66-4A0C-35F5-8D72-80D76A716A03> /usr/lib/libauto.dylib
0x9478c000 - 0x9485aff7  com.apple.backup.framework (1.5.4 - 1.5.4) <C09AF796-385F-34DB-B551-68967989E9CB> /System/Library/PrivateFrameworks/Backup.framework/Versions/A/Backup
0x94888000 - 0x948b2fff  libsandbox.1.dylib (278.11.1) <2F3D3000-58BE-38CD-A0C3-1845D93D174A> /usr/lib/libsandbox.1.dylib
0x948b3000 - 0x9491affc  com.apple.framework.CoreWLAN (4.3.3 - 433.48) <223A367D-1ADE-3CEA-8FE6-ACF3C1FFAB94> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
0x9493c000 - 0x94955fff  libAVFAudio.dylib (32.2) <A51776F2-0DCA-336D-8898-6876C63F8CDD> /System/Library/Frameworks/AVFoundation.framework/Versions/A/Resources/libAVFAudio.dylib
0x94956000 - 0x94957ffc  com.apple.TrustEvaluationAgent (2.0 - 25) <064B485D-56E0-3DD7-BBE2-E08A5BFFF8B3> /System/Library/PrivateFrameworks/TrustEvaluationAgent.framework/Versions/A/TrustEvaluationAgent
0x94ad7000 - 0x94b2aff3  com.apple.CoreMediaIO (408.0 - 4570) <0E0FFC14-2D70-369A-9399-DC7DDB6CCA79> /System/Library/Frameworks/CoreMediaIO.framework/Versions/A/CoreMediaIO
0x94b2b000 - 0x94b33fff  libsystem_dnssd.dylib (522.92.1) <51965446-5C40-3172-9766-C5AE7FD4D62E> /usr/lib/system/libsystem_dnssd.dylib
0x94b34000 - 0x94b90ffa  com.apple.print.framework.PrintCore (9.0 - 428) <3E248391-2669-328B-B84F-8763FE8E92BB> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/PrintCore
0x94b91000 - 0x94b95fff  libheimdal-asn1.dylib (323.92.1) <DD8BAEED-28AC-389E-9DC4-E32DA60CB05A> /usr/lib/libheimdal-asn1.dylib
0x94b96000 - 0x94d06fff  com.apple.QTKit (7.7.3 - 2826.24) <A9375DC8-01FE-3BF1-87E6-5595EC22AB4E> /System/Library/Frameworks/QTKit.framework/Versions/A/QTKit
0x94d07000 - 0x94d07ffd  libOpenScriptingUtil.dylib (157) <4D06E8ED-D312-34EA-A448-DFF45ADC3CE5> /usr/lib/libOpenScriptingUtil.dylib
0x94d08000 - 0x9512dfe3  com.apple.VideoToolbox (1.0 - 1273.54) <63E19724-B43E-3552-8D1F-87D0688DF593> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
0x9512e000 - 0x95174ff7  libFontRegistry.dylib (127) <A0930DB2-A6C6-3C6E-B4A2-119E0D76FD7D> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistry.dylib
0x95175000 - 0x95183ff7  com.apple.Sharing (132.2 - 132.2) <87DBFC7A-9689-3B8E-AD16-5A9DFF9DE625> /System/Library/PrivateFrameworks/Sharing.framework/Versions/A/Sharing
0x95184000 - 0x952f7ffb  com.apple.audio.toolbox.AudioToolbox (1.10 - 1.10) <4248C0FE-F872-34AB-9402-0045D5CD0CC1> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
0x952f8000 - 0x953defff  com.apple.coreui (2.2 - 231.1) <17E75125-8D14-30EF-B7A7-662A56B0F4B3> /System/Library/PrivateFrameworks/CoreUI.framework/Versions/A/CoreUI
0x953df000 - 0x953ebfff  libkxld.dylib (2422.115.4) <8B183287-E46E-3810-AA93-7A83E4BBEA2E> /usr/lib/system/libkxld.dylib
0x953ec000 - 0x954afff1  com.apple.CoreText (367.20 - 367.20) <42445623-3BDD-3678-8B46-845C441B6251> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
0x9550f000 - 0x95513ffa  libcache.dylib (62) <9730D7F2-D226-3F30-8D26-BF598CB781F6> /usr/lib/system/libcache.dylib
0x95514000 - 0x955c0ffb  libvMisc.dylib (423.32) <43873EFF-FB43-3301-BEE8-F2C3A046D7A6> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvMisc.dylib
0x955c1000 - 0x9583dfe7  com.apple.QuickTime (7.7.3 - 2826.24) <47052198-D890-3D54-80C6-953FE23AD04F> /System/Library/Frameworks/QuickTime.framework/Versions/A/QuickTime
0x9583e000 - 0x95842ffc  libpam.2.dylib (20) <50623D44-795F-3E28-AA85-23E0E7E2AE0E> /usr/lib/libpam.2.dylib
0x95843000 - 0x9588fff7  libcups.2.dylib (372.4) <A11AA954-07E7-3929-84AB-309B0C0DDB5D> /usr/lib/libcups.2.dylib
0x958d0000 - 0x95902ffb  com.apple.CoreAVCHD (5.7.0 - 5700.4.3) <30CF0E7B-3511-318F-AC31-06C29EDC111E> /System/Library/PrivateFrameworks/CoreAVCHD.framework/Versions/A/CoreAVCHD
0x95903000 - 0x95957fff  com.apple.AppleVAFramework (5.0.27 - 5.0.27) <85BCA1CF-9F7A-3AC1-AD58-4FABEA70A7D6> /System/Library/PrivateFrameworks/AppleVA.framework/Versions/A/AppleVA
0x959f7000 - 0x959faff7  com.apple.help (1.3.3 - 46) <AB6292FA-D3BC-3D56-B3A5-2BE630A503E7> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Help.framework/Versions/A/Help
0x95ab8000 - 0x95ae3ff5  com.apple.ChunkingLibrary (2.0 - 155.1) <50BBBBF8-F30B-39EA-A512-11A47F429F2C> /System/Library/PrivateFrameworks/ChunkingLibrary.framework/Versions/A/ChunkingLibrary
0x95ae4000 - 0x95af9ff3  com.apple.AppContainer (3.0 - 1) <017FED4F-AD6E-3A56-806B-A2D33E69EFF9> /System/Library/PrivateFrameworks/AppContainer.framework/Versions/A/AppContainer
0x95afa000 - 0x95b4dfff  com.apple.htmlrendering (77 - 1.1.4) <408FA30F-4FE9-3162-9FFD-677E8569C1EA> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HTMLRendering.framework/Versions/A/HTMLRendering
0x95f3c000 - 0x95f41ff7  com.apple.print.framework.Print (9.0 - 260) <A6C465F6-C5D1-353A-9F33-19B9CEDBBC2A> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Print.framework/Versions/A/Print
0x95f42000 - 0x95f49ff2  com.apple.NetFS (6.0 - 4.0) <915AA303-C02B-3B0C-8208-D8AAA4350DB4> /System/Library/Frameworks/NetFS.framework/Versions/A/NetFS
0x96871000 - 0x96872ffa  libsystem_sandbox.dylib (278.11.1) <DA875837-A5C2-3004-8117-65F378E4BD03> /usr/lib/system/libsystem_sandbox.dylib
0x96b9b000 - 0x96c33ff7  com.apple.Metadata (10.7.0 - 800.28) <8AF73B57-0FC2-3A11-9216-6A70D3C6A9EB> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata
0x96c34000 - 0x96f29ffc  com.apple.CoreImage (9.4.0) <33696A53-9E18-32D6-844F-28098DB7E426> /System/Library/Frameworks/QuartzCore.framework/Versions/A/Frameworks/CoreImage.framework/Versions/A/CoreImage
0x96f2a000 - 0x97322ffb  com.apple.CoreGraphics (1.600.0 - 599.35.4) <2B46D887-CAED-30F3-B009-1EBF0C71DC2E> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
0x97353000 - 0x9763dfd2  com.apple.vImage (7.0 - 7.0) <256972F0-3DBC-3CE1-9EE8-B48243868729> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/vImage
0x97642000 - 0x976c2ff7  com.apple.CoreServices.OSServices (600.4 - 600.4) <53C9C33B-B000-37FD-8C8F-C86F29F058F0> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices
0x97f02000 - 0x97f2cfff  libxslt.1.dylib (13) <249D54AB-1D82-38FE-ABEC-0D575450C73B> /usr/lib/libxslt.1.dylib
0x97f2d000 - 0x97f2ffff  com.apple.SecCodeWrapper (3.0 - 1) <066E1E30-2EEA-3166-8F86-D1054B50875B> /System/Library/PrivateFrameworks/SecCodeWrapper.framework/Versions/A/SecCodeWrapper
0x97f3e000 - 0x97f6aff7  com.apple.DictionaryServices (1.2 - 208) <33873336-BECD-3F62-A315-C45F24C1818C> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices
0x97f6b000 - 0x97fb3fff  com.apple.PerformanceAnalysis (1.47 - 47) <8041F84A-EC6F-3B5E-831E-87F6BCFB7073> /System/Library/PrivateFrameworks/PerformanceAnalysis.framework/Versions/A/PerformanceAnalysis
0x9803a000 - 0x9803cfff  libquarantine.dylib (71) <EE3B510E-1AEC-3171-8A1A-D6A5A42CF35C> /usr/lib/system/libquarantine.dylib
0x9803d000 - 0x98092ff7  com.apple.audio.CoreAudio (4.2.1 - 4.2.1) <CB06B746-9EB1-3972-A798-A139E15F5ACC> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
0x98093000 - 0x98109ff3  com.apple.securityfoundation (6.0 - 55122.3) <DFA5E047-2B68-3CE8-B9C3-D19E6F2461CB> /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation
0x9810a000 - 0x981faffb  libiconv.2.dylib (41) <848FEBA7-2E3E-3ECB-BD59-007F32468787> /usr/lib/libiconv.2.dylib
0x981fb000 - 0x98226ff7  libpcap.A.dylib (42) <66FBEAD3-FE91-3A89-8706-FB95229068AC> /usr/lib/libpcap.A.dylib
0x9822b000 - 0x9829efff  com.apple.SearchKit (1.4.0 - 1.4.0) <6F607AB6-7553-37BA-BEC5-98FD7C27FAD7> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit
0x9839b000 - 0x9839dffb  libRadiance.dylib (1044) <6713977E-A33A-395A-9933-719F72DF1A98> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libRadiance.dylib
0x99254000 - 0x9926cffd  libdispatch.dylib (339.92.1) <7E7A88BF-74B3-363B-B534-6F757DF2DDE3> /usr/lib/system/libdispatch.dylib
0x9928c000 - 0x992bcff7  com.apple.CoreServicesInternal (184.9 - 184.9) <999FEDEC-7657-3F32-A9AE-F29E0BE0AAF5> /System/Library/PrivateFrameworks/CoreServicesInternal.framework/Versions/A/CoreServicesInternal
0x992bd000 - 0x995eaffe  com.apple.Foundation (6.9 - 1056.16) <F4D43475-9915-3552-B8E1-4F3E1C9E5394> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
0x995eb000 - 0x995f9ff3  com.apple.opengl (9.6.1 - 9.6.1) <E9135C1E-4F15-3978-96FA-AA3EA0FE9CBE> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
0x995fa000 - 0x99622ff7  libRIP.A.dylib (599.35.4) <6E3B8709-162D-331E-8722-81D12B0A4BDB> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/Resources/libRIP.A.dylib
0x996be000 - 0x99750ff9  libsystem_c.dylib (997.90.3) <80D21D3D-1031-314C-B1F0-0B35B977CEFB> /usr/lib/system/libsystem_c.dylib
0x99751000 - 0x997edfff  com.apple.QD (3.50 - 298) <F73FD4D4-17A4-37D6-AC06-7CA5A8BA1212> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/QD.framework/Versions/A/QD
0x997ee000 - 0x998c9ff7  com.apple.LaunchServices (572.28 - 572.28) <12F13478-DB82-3C78-9140-2C98FECD0A80> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
0x998ca000 - 0x9991aff7  libcorecrypto.dylib (161.1) <135FD99E-2211-3DF4-825C-C9F816107F0C> /usr/lib/system/libcorecrypto.dylib
0x9991b000 - 0x99c1cffb  com.apple.CoreServices.CarbonCore (1077.17 - 1077.17) <02C72D54-E3D3-32B0-A081-E85A7038489D> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
0x99c1d000 - 0x99c6cff9  com.apple.HIServices (1.23 - 468) <E8F6C5CD-F96C-3E81-B8B4-2811BBAC222F> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices
0x99eda000 - 0x99edcfff  com.apple.securityhi (9.0 - 55005) <7B106CFE-C811-3350-B4E7-F5763F6B698F> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SecurityHI.framework/Versions/A/SecurityHI
0x99ef4000 - 0x99ef9ff3  libsystem_platform.dylib (24.90.1) <0613F163-9A7A-3908-B30B-AC1627503933> /usr/lib/system/libsystem_platform.dylib
0x99f36000 - 0x9a19aff7  com.apple.CoreData (107 - 481.3) <8EB45FB9-CF78-36E1-919C-E976AE4C8146> /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
0x9a19b000 - 0x9a1a5ff2  com.apple.AppSandbox (3.0 - 1) <FE0793BE-50CF-3E3B-82C9-71F7A294E10F> /System/Library/PrivateFrameworks/AppSandbox.framework/Versions/A/AppSandbox
0x9a1a6000 - 0x9a210ff7  com.apple.framework.CoreWiFi (2.0 - 200.21.1) <13EE6C12-B981-3132-864A-D493B91AE37E> /System/Library/Frameworks/CoreWiFi.framework/Versions/A/CoreWiFi
0x9a211000 - 0x9a33eff3  com.apple.avfoundation (2.0 - 651.12.1) <6A8A6D6F-87E0-3514-BB0C-E3659542A857> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
0x9a33f000 - 0x9a6aefff  com.apple.MediaToolbox (1.0 - 1273.54) <46C11BBD-7F31-3227-9441-6087FAA3B477> /System/Library/Frameworks/MediaToolbox.framework/Versions/A/MediaToolbox
0x9a6e0000 - 0x9a6f3fff  com.apple.ImageCapture (9.0 - 9.0) <63D5C96F-1893-3F35-ADFB-EE451AFD87E6> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/ImageCapture.framework/Versions/A/ImageCapture
0x9a7fd000 - 0x9a7fefff  libDiagnosticMessagesClient.dylib (100) <B936B1D4-90BB-395D-8EA9-E1237608E7D0> /usr/lib/libDiagnosticMessagesClient.dylib
0x9a7ff000 - 0x9a8cffef  libvDSP.dylib (423.32) <E2FA7230-A001-3F6B-9ACF-6998C51AD7DC> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvDSP.dylib
0x9a8d0000 - 0x9a8d2ffe  libCVMSPluginSupport.dylib (9.6.1) <DCEA5FE5-AC05-3B1A-B87E-1FB8E0CAAFFF> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCVMSPluginSupport.dylib
0x9a8d3000 - 0x9aa7ffff  com.apple.QuartzCore (1.8 - 332.3) <1A14CA72-68A2-3970-BFF6-3D36339496FB> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
0x9aa81000 - 0x9aa81fff  com.apple.Carbon (154 - 157) <6C29C608-97B4-306E-AEC5-6F48EDF7EFB5> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
0x9aa82000 - 0x9aac2ff7  com.apple.bom (14.0 - 193.1) <FFF1C8E5-41FF-357B-8681-69B21DCED2E4> /System/Library/PrivateFrameworks/Bom.framework/Versions/A/Bom
0x9aac3000 - 0x9aac8fff  com.apple.MediaAccessibility (1.0 - 43) <1CC2B661-146A-3FF3-B843-508F611F7B4B> /System/Library/Frameworks/MediaAccessibility.framework/Versions/A/MediaAccessibility
0x9aac9000 - 0x9ab2fffb  com.apple.CoreUtils (2.0 - 200.34.4) <F14AAB3C-1C8A-37D7-85BE-76646F9F6098> /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
0x9ab30000 - 0x9ab36ffb  libunwind.dylib (35.3) <099D1A6F-A1F0-3D05-BF1C-0A7BB32D39C2> /usr/lib/system/libunwind.dylib
0x9ab37000 - 0x9abc1ff7  com.apple.CoreSymbolication (3.0.1 - 141.0.5) <996E5777-1F98-3841-9614-5FC5E03589E3> /System/Library/PrivateFrameworks/CoreSymbolication.framework/Versions/A/CoreSymbolication
0x9abcd000 - 0x9abcefff  liblangid.dylib (117) <F18F76C6-7E4B-34AD-AE81-C1C031BF2F7D> /usr/lib/liblangid.dylib
0x9abd1000 - 0x9ad97ffb  libicucore.A.dylib (511.35) <D14DF7FE-7DE3-36C6-A46D-18C3978827A5> /usr/lib/libicucore.A.dylib
0x9ada0000 - 0x9ada8fff  libcopyfile.dylib (103.92.1) <9B62DDFE-FEFD-31CA-989F-9BE0AB606C49> /usr/lib/system/libcopyfile.dylib
0x9ada9000 - 0x9adb0fff  libMatch.1.dylib (19) <3B3680FC-2AC9-37CC-B262-5ACE2CF8939A> /usr/lib/libMatch.1.dylib
0x9adb1000 - 0x9adbbfff  com.apple.bsd.ServiceManagement (2.0 - 2.0) <B84F3916-236A-347B-9C1F-3DE571496737> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
0x9af87000 - 0x9b094ff7  com.apple.ImageIO.framework (3.3.0 - 1044) <D48549F6-CD49-30FA-A4CD-85166A66D830> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
0x9b095000 - 0x9b09cffb  libsystem_pthread.dylib (53.1.4) <8B1B7B84-1B5D-32A8-AC0D-1E689E5C8A4C> /usr/lib/system/libsystem_pthread.dylib
0x9b09d000 - 0x9b0daffb  libGLImage.dylib (9.6.1) <E2DADD8A-8A60-3F39-840B-4B7FE7001384> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLImage.dylib
0x9b0db000 - 0x9b0e7ffc  libbz2.1.0.dylib (29) <3CEF1E92-BA42-3F8A-8E8D-9E1F7658E5C7> /usr/lib/libbz2.1.0.dylib
0x9b0e8000 - 0x9b151fff  com.apple.SystemConfiguration (1.13.1 - 1.13.1) <68986435-5B12-370A-9408-0282D176279F> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
0x9b152000 - 0x9b16bfff  com.apple.Kerberos (3.0 - 1) <91F17EB2-C70C-359C-B09D-96B52D2A9C9F> /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos
0x9b16c000 - 0x9b36efff  com.apple.CoreFoundation (6.9 - 855.17) <E382BBB6-4F41-3959-ADC7-238BE49A2155> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
0x9b36f000 - 0x9b378ff7  libsystem_notify.dylib (121.20.1) <4D3293AC-1CEF-347A-987F-2314AF3CC6EA> /usr/lib/system/libsystem_notify.dylib
0x9b37c000 - 0x9b37cffd  com.apple.audio.units.AudioUnit (1.10 - 1.10) <9515158F-3A33-39CF-AD5A-201C2B121F33> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
0x9b430000 - 0x9b438ffe  libGFXShared.dylib (9.6.1) <D1A3DB40-7F78-36A9-A4FB-BC1A875F94DC> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGFXShared.dylib
0x9b439000 - 0x9b43dff7  libmacho.dylib (845) <D8E93E59-1F80-3413-B9CF-78B848F6E873> /usr/lib/system/libmacho.dylib
0x9b43e000 - 0x9b44cff7  libz.1.dylib (53) <858B4D9F-D87E-3D81-B07A-DF9632BD185F> /usr/lib/libz.1.dylib
0x9b452000 - 0x9b4abffa  libTIFF.dylib (1044) <EC7E978B-3A38-3696-AAB6-A32221952C69> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libTIFF.dylib
0x9b4b2000 - 0x9b4c4fff  libbsm.0.dylib (33) <1BE92DB5-0D2F-3BB5-BCC6-8A71EF2A3450> /usr/lib/libbsm.0.dylib
0x9b740000 - 0x9b7a9ffa  com.apple.datadetectorscore (5.0 - 354.5) <2B523979-8292-3132-96AB-79274908CD2F> /System/Library/PrivateFrameworks/DataDetectorsCore.framework/Versions/A/DataDetectorsCore
0x9b7aa000 - 0x9b7b3ffc  com.apple.CommonAuth (4.0 - 2.0) <99219CEB-D340-3E1F-9C04-FD0FA700BD67> /System/Library/PrivateFrameworks/CommonAuth.framework/Versions/A/CommonAuth
0x9b7b4000 - 0x9b7b7ff9  com.apple.TCC (1.0 - 1) <A5FCF7AA-3F56-3A19-9DF1-661F1F02F79D> /System/Library/PrivateFrameworks/TCC.framework/Versions/A/TCC
0x9b7b8000 - 0x9b7c6fff  libxar.1.dylib (202) <B73748D4-F830-3C71-98B3-7A3ABF5136FD> /usr/lib/libxar.1.dylib
0x9b7c7000 - 0x9b7c7fff  com.apple.Accelerate.vecLib (3.9 - vecLib 3.9) <DDAC0B59-F886-3AB1-98E8-C71FFF161CD4> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
0x9b7c8000 - 0x9b818fff  com.apple.opencl (2.3.59 - 2.3.59) <CE95AA26-7AE6-3692-8291-8268BBB976D1> /System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL
0x9b8cf000 - 0x9b9e1ffc  libsqlite3.dylib (158) <B3DB0FED-FE4C-314D-8329-CF7708C8AAF4> /usr/lib/libsqlite3.dylib
0x9b9e2000 - 0x9b9e3fff  libsystem_blocks.dylib (63) <2AC67D5E-ECD4-3644-A53C-9684F9B7AA33> /usr/lib/system/libsystem_blocks.dylib
0x9b9e4000 - 0x9ba08fff  libJPEG.dylib (1044) <8501702E-37C9-35F6-8342-037337CCD837> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJPEG.dylib
0x9ba09000 - 0x9ba80ffb  com.apple.framework.IOKit (2.0.1 - 907.100.13) <D1308EE0-96AA-3442-A27B-264F58AE12B4> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
0x9ba81000 - 0x9bdf6ff9  com.apple.HIToolbox (2.1.1 - 698) <392738F0-322F-3C80-BEF7-138AFB124C35> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
0x9bdf7000 - 0x9be1bff7  libxpc.dylib (300.90.2) <5ACBBE2C-74EB-3E88-BCBF-C573095318A5> /usr/lib/system/libxpc.dylib
0x9be1c000 - 0x9c1e1ff6  libLAPACK.dylib (1094.5) <E6286E68-3501-31AC-813E-75B3B3968011> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
0x9c211000 - 0x9c225ff9  com.apple.MultitouchSupport.framework (245.13.1 - 245.13.1) <6DDC6828-879B-3F7F-9458-8F57713104B5> /System/Library/PrivateFrameworks/MultitouchSupport.framework/Versions/A/MultitouchSupport
0x9c22f000 - 0x9c25aff7  libsystem_network.dylib (241.3) <71EBA489-386D-3608-ADE6-CB50EBD1AB1B> /usr/lib/system/libsystem_network.dylib
0xba900000 - 0xba91cffd  libJapaneseConverter.dylib (61) <3153973E-B2A9-3D17-B99B-31E53EC5B0F8> /System/Library/CoreServices/Encodings/libJapaneseConverter.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 1
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 161
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=154.5M resident=39.3M(25%) swapped_out_or_unallocated=115.2M(75%)
Writable regions: Total=52.3M written=2108K(4%) resident=3912K(7%) swapped_out=0K(0%) unallocated=48.4M(93%)
 
REGION TYPE                      VIRTUAL
===========                      =======
CG backing stores                   112K
CG shared images                    180K
CoreServices                       1048K
Kernel Alloc Once                     4K
MALLOC                             40.7M
MALLOC (admin)                       48K
Memory Tag 242                       12K
Stack                              65.6M
VM_ALLOCATE                        1328K
__DATA                             14.8M
__IMAGE                             528K
__LINKEDIT                         43.5M
__OBJC                             2184K
__PAGEZERO                            4K
__TEXT                            110.9M
__UNICODE                           544K
mapped file                       142.1M
shared memory                         4K
===========                      =======
TOTAL                             423.5M

Model: MacPro5,1, BootROM 144.0.0.0.0, 4 processors, 1 GHz, 2 GB, SMC 1.74f4
Graphics: Display, PCI, 3 MB
Memory Module: DIMM 0, 2 GB, RAM, 0 MHz, QEMU, Unknown
Network Service: RNDIS/QEMU USB Network Device, Ethernet, en0
Serial ATA Device: QEMU HARDDISK, 68.72 GB
Serial ATA Device: QEMU DVD-ROM, 7.67 GB
USB Device: QEMU USB HARDDRIVE
USB Device: QEMU USB Keyboard
USB Device: QEMU USB Mouse
USB Device: QEMU USB Tablet
USB Device: QEMU USB Keyboard
USB Device: RNDIS/QEMU USB Network Device
Thunderbolt Bus: 

[config.plist.zip](https://github.com/utmapp/UTM/files/10608690/config.plist.zip)

**Comment by Rastafabisch** [comment]
I can confirm the issue with OS X Mavericks.
I also tested the predecessor OS X Mountain Lion, which does not have the same issue. 32bit Apps work just fine. 
<img width="1128" alt="Bildschirm­foto 2023-02-16 um 19 04 45" src="https://user-images.githubusercontent.com/38974866/219450257-aa075209-1f58-413b-b3c4-87c4599ab76f.png">

**Comment by Rastafabisch** [comment]
I fixed the issue!
Apparently the OpenCore EFI configuration caused this. I updated OpenCore and the config and now it works again.
<img width="1426" alt="Bildschirm­foto 2023-02-16 um 21 31 53" src="https://user-images.githubusercontent.com/38974866/219480321-d554098e-a7ac-4806-a2c0-078dcda15c5a.png">

[EFI-LEGACY.qcow2.zip](https://github.com/utmapp/UTM/files/10760561/EFI-LEGACY.qcow2.zip)

**Comment by pedroponchojr** [comment]
Thank you very much for your kind and to-the-point replies. I had thought I might be the only one to have such a problem, so your responses greatly eased my mind.

I've also tested your suggestions. I will report the results here. First, I have successfully installed Mavericks using your OpenCore-EFI.qcow2. However, no 32bit applications were able to start again. I have tried DVD Player and Mariner Calc. I attached a crash report of DVD Player.

Second, I have managed to get Moutain Lion onto UTM and this time I had no trouble with any 32bit applications, as you mentioned. I have tried the following applications:

Bento					
File Buddy				
eReader
Grapher					
Mariner Calc				
Oxford Learner's Thesaurus
Parallels Transporter		
Tex-Edit Plus			

So far I have had no problem at all with them.

Again, thank you so much for what you have done to me, a complete stranger. I hope my information will be of some use.
[Crash report of DVD Player.txt](https://github.com/utmapp/UTM/files/10775448/Crash.report.of.DVD.Player.txt)

**Comment by pedroponchojr** [comment]
Sorry I forgot to add config.plist from my Mavericks virtual machine.
[config.plist.zip](https://github.com/utmapp/UTM/files/10775544/config.plist.zip)

**Comment by arekkusu42** [comment]
This was closed (assuming EFI update resolved the problem) but it is not fixed.
Still occurs with UTM 4.4.5 and 4.5.1b, when running any 32-bit GUI application in newer macOS guests.

I have isolated the root cause. The problem is not limited to 32 bit apps and also crashes the 64-bit WindowServer when attempting to log in to El Capitan, as described in #5371 
[4.3.0 Beta, M1 Host, OS 10.11 guest - hangs in terminal window when booting](https://github.com/utmapp/UTM/issues/5371#issue-1742240264)
That issue is still open, so adding comments there.
