### ISSUE TITLE
MacOS crashes right on trying to force reboot on freeze

### ISSUE THREAD

**Issue by Pixel556** [utmapp/UTM#5605]
**BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**Describe the issue**  
Windows VMs sometimes freeze randomly. For example:
My Windows 10 x64 VM freezed when I was trying to render a webpage in Edge. (This was expected cause QEMU is slow)
And my Windows 11 VM freezed when I was trying to use  a Windows CE emulator, and messed with the settings a bit
Option+command (attach cursor to VM) shows that the entire VM is frozen INCLUDING the cursor.
Trying to force reboot/ force shutdown results in a longer loading sequence than usual and shows an error:
_**Timed out waiting for RPC**_
The app then freezes and hangs at the beachball. Force quitting and reopening fixes this.

**Configuration**  
* UTM Version: 4.2.5 (B1)
* macOS Version: Ventura 13.4
* Mac Chip (Intel, M1, ...): M1

**Crash log**  
There is no crash log, just hangs at the beachball

**Comment by 0f2g** [comment]
Similar issue here; However, I am more concerned with the VM freezing, rather than the UTM application crashing.

1. Virtual Machine (Windows 11 Enterprise) freezes
2. UTM displays Error: Timed out waiting for RPC
3. UTM Application Crashes

_I am thinking this is a glitch with either the WebDAV or Disk Image emulation._ 

Host:
- macOS Version: Sonoma 14.6.1 (23G93)
- Mac Chip (Intel, M1, ...): Apple M3 Max
- Memory: 36 GB

Application
- UTM Version: Version 4.5.3 (99)

Virtual:
- Architecture: ARM64
- System (Machine): QEMU 7.2 ARM 
- Memory: 6 GB
- CPU: Default
- Cores: Default
- Force Multicore: OFF
- JIT Cache: Default
- UEFI Boot: Enabled
- RNG Device: Enabled
- Balloon Device: OFF
- TPM 2.0 Device: Enabled
- Use Hypervisor: Enabled
- Use Local time: Enabled
- Force PS/2: OFF
- QEMU Machine Properties: Default
- USB Support: USB 3.0 (XHCI)
- Clipboard Sharing: Enabled
- Directory Share Mode: SPICE WebDAV

- Disk Image Interface: NVMe
- Disk Image Size: ~36 GB

**Comment by HenrikVL** [comment]
I have the same issue. It often ends in "Timed out waiting for RPC". To me, I have to restart the UTM application before starting the VM again. 
I am running Kali Linux on a M1 Macbook Pro.

**Comment by 0f2g** [comment]
The issue appears directly related to some sort of bug/issue with the VM accessing the same (overlapping) real local file system directory structure as another VM or application, (freezing after a short period). 

When I avoid either reading or writing files outside the VM, then the VM appears to remain stable indefinitely. 

Another two annoyances I have encountered are:
1) The keyboard occasionally refusing to accept specific letters — fixed by either restarting or forcing focus towards & away & back to the VM.
2) An inability to “suspend” the VM — fixed by enabling hibernation, then powering off the VM; this allows resuming most previous activities.

**Comment by keysteal72** [comment]
I'm having the same issue with latest release.

**Comment by keysteal72** [comment]
This issue persists also with the beta release 4.7.0

**Comment by Valadaress** [comment]
Still with this issue. The VM freezes periodically and when I try to shutdown it show the error message.

Device:
Mac Studio M3 Ultra

**Comment by vishal-1230** [comment]
Same here, Issue still persists, randomly (mostly while running any browser, firefox etc.)

Config:
OS - Debian
Device - Mac M4, 16GB

Any logs, that we can provide?? to help debug the issue?
