### ISSUE TITLE
Crash on start VM

### ISSUE THREAD

**Issue by WongIong** [utmapp/UTM#95]
**Message from developer: I'm hijacking this issue to point out this common problem. UTM does NOT work with AppCake and many similar "cloud" signing services! You can either use a Filza + a jailbroken device to install the fakesigned IPA release OR follow the resign instructions in the README to install on a stock device.**

UTM 0.3
iPad Air 3 64GB on 12.4 jailbroken
I tried XP, 7
RAM 1024/2048 both tried
Disk 20480MB
These settings can work on my iPhone11 Pro Max but ram should be 1024
It may cause by A12?

**Comment by osy86** [comment]
Please attach a crash log. https://stackoverflow.com/questions/24400414/how-to-locate-app-crash-logs-in-iphone-ipad

**Comment by WongIong** [comment]
[UTM-2020-03-03-103447.zip](https://github.com/utmapp/UTM/files/4280430/UTM-2020-03-03-103447.zip)
Please change the .zip to .ips

**Comment by osy86** [comment]
Did it work on v0.2?

**Comment by osy86** [comment]
How did you sign/install the IPA?

**Comment by WongIong** [comment]
nope, this issue begins from v0.2, but 0.1 is working
I downloaded it by safari and opened in Reprovision or Appcake, both are not working

**Comment by osy86** [comment]
Can you try smaller ram? Maybe 256MB?

**Comment by WindowsBetaTest** [comment]
My iPad 5 is always like this after jailbreak. You can try to install UTM again without jailbreak.

**Comment by WongIong** [comment]
Ph, i found out the problem. If i use Appcake or Reprovision to resign the app, than it will crash. But if I use jailbroken Filza to install it, it works.

**Comment by WongIong** [comment]
Shit, when i restart my ipad. The problem comes again!!!

**Comment by osy86** [comment]
Filza installs the fakesigned version which requires jb. Did you jb after rebooting?

**Comment by WongIong** [comment]
Sure, and crashes happen only after VM launch.
Non jb environment will crash the app on tapping icon.

**Comment by osy86** [comment]
Do you know if v0.1 worked after VM launch?

**Comment by WongIong** [comment]
Haha, as i mentioned above, yes. And I can also use Appcake or Reprovision to sign it.

**Comment by osy86** [comment]
Sorry, lots of issues to keep track of. Okay I will make a new build for you to test.

**Comment by osy86** [comment]
Please try https://mega.nz/#!JsoDWYpS!2EUuQP2V4WjDSYBVx0umdvdfwpA8SIBTi0sVYaqlVJU

**Comment by WongIong** [comment]
V0.3
= =Sorry for that you make a new build, but i have to say...
This time's reboot couldn't reproduce that. it is working= =
This is so odd...

**Comment by osy86** [comment]
So new build vs 0.3, no difference?

**Comment by WongIong** [comment]
wait, i have not tried the new build.

**Comment by WongIong** [comment]
till now, new build doesn't crash at all.
But I think we should test it for a longer time.
I will give a feedback in here.
BTW. how can i use the network inside the VM? I don't know how to set it up.

**Comment by osy86** [comment]
https://github.com/utmapp/UTM/wiki/Known%20Issues

Please test new build the same way as before (jb vs non-jb, Appcake, Reprovision, filza, etc) and report all results.

**Comment by WongIong** [comment]
After the last time’s launching, i just charged my ipad.
But now the new build is crashing too...
No crashing log in ios analysis .

**Comment by miuirussia** [comment]
[UTM-2020-03-05-221731.zip](https://github.com/utmapp/UTM/files/4294760/UTM-2020-03-05-221731.zip)
Had same issue

**Comment by osy86** [comment]
@miuirussia is this with the new build https://github.com/utmapp/UTM/issues/95#issuecomment-594795740

**Comment by miuirussia** [comment]
I tried it.

iOS 13.4
iPhone 11 Pro Max

**Comment by ljzxzxl** [comment]
iPad Pro 11 iOS13.4
Crash on start VM  with memory 512MB and 1024MB

**Comment by osy86** [comment]
Please post crash log.

**Comment by ljzxzxl** [comment]
Logs:
http://xeylon.com/logs/UTM-2020-03-09-162658.ips
http://xeylon.com/logs/UTM-2020-03-09-162854.ips
http://xeylon.com/logs/UTM-2020-03-09-165003.ips

**Comment by ljzxzxl** [comment]
@osy86 Please download these logs as soon as possible, I will delete them in a while.

**Comment by osy86** [comment]
Is this jailbroken? How are you signing?

**Comment by osy86** [comment]
@ljzxzxl Please try this special build https://mega.nz/#!Zh5mFAhA!k8krwJjhSOfh_y0MyAlfz301g82R1G23o9QiwWM9q6Q
Tell me if you see a message on startup.

**Comment by ljzxzxl** [comment]
@osy86 I tried the version you said of mega, but the problem remains.  
I installed utm through the iphonecake app, this is the way of auto signature
When I first start UTM here is zhe message.
http://xeylon.com/logs/20200310111210.jpg
logs
http://xeylon.com/logs/UTM-2020-03-10-110730.ips

**Comment by Papyrusman** [comment]
I had a similar issue which was resolved after realizing when I created the virtual hard drive I did not add “.img” to the end of the file name.
Crash on first start.

**Comment by Charlotte885** [comment]
I decided to create a account after trying your app.

Both my iPhone SE and ipad 6 gen crash.

I tried few way and it crashes for all

1. Create a VM with just the VM name and try click start 
2. Create a VM with VM name and also the ISO only without putting hda.img
3. Create a VM with VM name and also the ISO only with putting hda.img


other information 

The iso i using is window XP
Memory tried ( 128,256,512)
hda.img size was 20480MB ( tried with both expending option on and off)


IPHONE SE available is 22GB
My ipad too Low storage so I thought it might be crashing because of that but did try number 1 and 2 also it did crash.

**Comment by osy86** [comment]
@Charlotte885 did you enter your memory in MB?

**Comment by Charlotte885** [comment]
@osy86 yup I did, 512 MB is set default for the app that what I notice. So I did reduce down to 256MB and 128MB. It still crashes.

**Comment by osy86** [comment]
It seems like AppCake does NOT work in signing UTM. Anyone experiencing this issue, please try installing with Filza instead and post here your results.

**Comment by Charlotte885** [comment]
Filza requires jail breaking the device right ?

**Comment by osy86** [comment]
No, there’s no issue afaik with non-jb signed with a developer certificate.

**Comment by Andy245** [comment]
13.3.1无法安装Filza

**Comment by osy86** [comment]
Those with this issue please dump the non-working installed .app from your jailbroken device, ZIP it and attach it here. Also mention how you re-signed it. Thanks.

**Comment by Chsengni** [comment]
When IOS 13.3.1 is turned on, vm flashes back for 6S

**Comment by Andy245** [comment]
现在创建虚拟机后点击启动可以进入，然后闪退

**Comment by Andy245** [comment]
13.4通过appcake签名

**Comment by ljzxzxl** [comment]
The same situation,Never successfully entered a virtual machine,Crash on start everytime on every UTM version Including the latest 0.7
iPad Pro 11, iOS 13.4 GM

**Comment by osy86** [comment]
@ljzxzxl can you dump the installed ipa? You can copy it from the device if you’re jailbroken. Or you can use ifunbox to “back up ipa”.

**Comment by ljzxzxl** [comment]
Hi @osy86 
The software ifunbox you said is too old, only supports systems below iOS8.3, and cannot export IPA.
I really want to help you solve this problem. I am a web developer. I have enough conditions to cooperate with you to reproduce the bug and solve this problem. Can we establish a timely contact in some way? By controlling my device remotely

**Comment by ljzxzxl** [comment]
I am using discord as user ljzxzxl and you can find me

**Comment by osy86** [comment]
I was able to confirm that AppCake and similar "cloud" signing services are NOT compatible with UTM as they do not sign with the proper entitlements.

**Comment by Charlotte885** [comment]
You are right, AppCake will not work.

But I can confirm alt store do work.

**Comment by Charlotte885** [comment]
@osy86 by the way, what did u configure (such as ram and cores, .etc) in your window XP to make it run that smooth. Because I saw the UTM website. The XP run really well.

**Comment by Andy245** [comment]
> 没错，AppCake无法正常工作。
> 
> 但我可以确认Alt Store是否可以正常工作。

Alt Store你是怎么弄的,有下载链接吗,我的iPad13.4安装过程报错

**Comment by mulra02** [comment]
I know that issue has been closed. I wanted to let you know that I had been experiencing crashes and the latest version seems to work for me. I am using appdb to sign and install.

**Comment by maxdbarton97** [comment]
Crashing for me too, and I am using xcode to sign it.

**Comment by iiGiovanni** [comment]
I got the same issue

If you create a virtual machine for Windows XP and you try to start it, it crashes immediately as soon as you try to start it.  I can do this on with iPhone 11 Pro Max without any problems.

Error log:

2020-04-01 03:08:41.766 UTM[4532:1768347] -[CSConnection init]:236
2020-04-01 03:08:41.772 UTM[4532:1768347] Loading libqemu-system-x86_64.dylib
2020-04-01 03:08:41.841 UTM[4532:1768347] Running:  qemu -L /private/var/containers/Bundle/Application/CA4B4E83-6FA8-40DD-AAAA-167D82FB1B30/UTM.app/qemu -qmp tcp:localhost:4444,server,nowait -smp cpus=1,sockets=1 -machine pc-i440fx-4.2 -accel tcg,thread=multi -vga qxl -boot order=d -m 1024 -soundhw ac97 -name Windows XP -drive file=/private/var/mobile/Containers/Data/Application/DB01F71C-333D-4162-A830-A7675D041275/Documents/Windows XP.utm/Images/WXPVOL_EN.iso,if=ide,media=cdrom,id=drive0 -drive file=/private/var/mobile/Containers/Data/Application/DB01F71C-333D-4162-A830-A7675D041275/Documents/Windows XP.utm/Images/hda.img,if=ide,media=disk,id=drive1 -spice port=5930,addr=127.0.0.1,disable-ticketing,image-compression=off,playback-compression=off,streaming-video=off -device rtl8139,netdev=net0 -netdev user,id=net0 -device usb-ehci -device usb-tablet

**Comment by maxdbarton97** [comment]
Why has this issue been closed? I am signing my build viar archive & ad hoc distribution with my professional developer account through xcode, and I am still crashing on run. Am I doing something wrong? If so I'd like to know what I need to get it working properly.

**Comment by osy86** [comment]
As mentioned in both the readme and in

**Comment by nfsking2** [comment]
Signing UTM latest .ipa file with iOS developer certification, the UTM app still crashed when starting the VM.

**Comment by osy86** [comment]
Yes hence #397 is stickied.

**Comment by rongtianjie** [comment]
I can open UTM but I have my utm crashed when I loaded a prebuild VM.

iPad Pro 2020 with iPadOS 14 beta5
installed and signed UTM with Altstore.
VM: Ubuntu 18.04 with default setting
Also try other VMs but all crashed.

[UTM-2020-08-19-101209.zip](https://github.com/utmapp/UTM/files/5098157/UTM-2020-08-19-101209.zip)

**Comment by ThatsNiceGuy** [comment]
@rongtianjie You cannot run UTM on iOS 14 without attaching a debugger from a Mac with Xcode.

**Comment by osy86** [comment]
shit

**Comment by osy86** [comment]
to boost

**Comment by r0my** [comment]
Hello,

i have the same problem here. iPhone 11 Pro Max, iOS 13.6, jb with newest uncover. AppSync Unified 104.0 is installed.

On my iPhone 8, there where no problems. UTM runs fine there. 

I Downloaded UTM from repo, but app crashes after respring/reboot and starting app.
So i deinstalled the app over cydia, reboot, and installed it again with filza, but the same problem again. 

Does anybody know, what the problem is?  
And can i help to figure out to locate the problem? 

Romy

**Comment by WXACN24** [comment]
Hello! This is an automatic reply email!It means I have successfully received your email!I will reply to your email within a few days.Have a nice day!This is my personal blog
